bigcommerce/dev-docs

markdown/stencil-docs/installing-stencil-cli/installing-stencil.md

The in context anchors (not OTP anchors) were not working on installing stencil for the following anchors: mac, windows, and linux. 
i changed them to match the structure of the in context anchors that exist in the localization article, which is using div ids instead of <a> tags.

remove non-working anchors and add div IDs to fix the scroll issue 

---

markdown/stencil-docs/reference-docs/stencil-utils-api-reference.md

Accidentally used name instead of id for the links. Stoplight uses id to created links in markdown.

Emergency fix 

---

markdown/api-docs/getting-started/webhooks/setting-up-webhooks.md

URL for ngrok web interface is served over http instead of https

Fix ngrok web interface URL

---

beta-documentation/refunds-api-PROJECT-2776/refunds.json
beta-documentation/refunds-api-PROJECT-2776/refunds.yaml
beta-documentation/refunds-api-PROJECT-2776/refunds_documentation.md

- added a beta folder. Thought it might be easier to keep any beta projects in one place instead of trying to hunt for them in the production documentation. Also makes sure we know this is a beta doc.
- added placeholder for swagger and markdown file

DEVDOCS-1059 Refunds API

---

markdown/stencil-docs/installing-stencil-cli/installing-stencil.md

Fixed link in installing-stencil

Added correct link to installing-stencil

---

beta-documentation/refunds-api-PROJECT-2776/returns.json

* Added new file called `returns.json` for returns settings and other returns API resources

Add returns swagger file with settings resource

---

spec/json/BigCommerce_Shipping_Provider_API.oas2.json

Removed inaccessible fields in shipping provider API. As per @vborinsk we should hide them until theyre accessible and integrated properly in the API

removed inaccessible fields

---

beta-documentation/returns-api-PROJECT-2776/returns.json

* use reference_id instead of order_product_id
* update resource names
* fix descriptions

Use updated naming in returns documentation; introduce reference ID

---

markdown/bigcommerce-for-wordpress/setup/shortcodes.md

Added description for BigCommerce Product Components and corresponding shortcode table
[BigCommerce product components](https://github.com/bigcommerce/bigcommerce-for-wordpress/blob/master/src/BigCommerce/Shortcodes/Product_Components.php)

added table outlining additional shortcodes for BC components

---

markdown/stencil-docs/installing-stencil-cli/installing-stencil.md

as discussed in friday sprint planning, changed title of Authorizing and Initializating Stencil CLI to be "Installing Stencil CLI"
-no ticket, but was talked about during sprint planning on august 3rd

change h1 to be installing stencil cli 

---

markdown/stencil-docs/reference-docs/common-objects.md

Removed
- ratings
- map_price
Added type and example to some objects
added to price object. returns as retail price now. 
Changed formatting from html tables to markdown tables
Used `debug=context` to check data
added note to price about enabling tax settings to see all price options

DEVDOCS-554 Catalog Price and Common Product Card Model table styling

---

spec/json/BigCommerce_Storefront_Checkout_API.oas2.json

- change customfields to use the model CustomFields. It already explained the field can be an array or a string
- added number to string in request and response

DEVDOCS-1107 Updated Billing Address to use CustomFields

---

spec/json/BigCommerce_Shipping_Provider_API.oas2.json

- Updated the `attributes object` under the `rate request item` to be an array of objects instead of an object. 
- Add `Attribute Value` model
- Updated `Base Rate Request`, `Rate Request Object` and `Rate Request Item` to describe the attributes array.

Update Shipping Provider API docs to reflect new Attributes object

---

markdown/stencil-docs/reference-docs/global-objects-and-properties.md

* Made it clear that the Object Properties in the Categories section are for the individual categories in the array
* Added usage example that shows how the name property can be used to render a list of category names for the given page context

Fix Categories Object and Add Example

---

spec/json/BigCommerce_Storefront_Token_API.oas3.json

Quick fix from a slack convo with @bookernath, so no ticket for this one. 
* Added closed beta in a few spots on the Storefront Token API spec
* Fixed the store_hash variable while I was there

Mark Storefront Token API as Closed Beta

---

markdown/api-docs/cart-and-checkout/embedded-checkout-overview.md
markdown/api-docs/cart-and-checkout/embedded-checkout-tutorial.md

* Fixed some broken HTML in the embedded checkout overview in tutorial that was causing the page to be scrunched to the right.

Fix Broken HTML in Embedded CO Content

---

markdown/bigcommerce-for-wordpress/extending-the-plugin/amp-for-the-plugin.md

* renamed the file from `new-subpage.md` to `amp-for-the-plugin.md` (also changed in stoplight)
* Moved classic mode section below paired and native mode and added a callout mentioning that its legacy.

Label AMP Plugin Classic as Legacy, Rename File

---

spec/json/BigCommerce_Store_Content_API.oas2.json

* Blog post put and post requests only accept RFC-2822 formatted dates as a flat string, even though the response contains a date object with an ISO 8601 formatted date
* Changed the examples, schemas, and properties in the spec to reflect dates accurately.

DEVDOCS-1169: Fix Dates in Blog Post Put and Post

---

markdown/api-docs/getting-started/authentication.md
spec/json/BigCommerce_Wishlist_API.oas2.json

Add Oauth scope needed to access Wishlists API in spec and in APi docs under authentication

DEVDOCS 1102 add information about Wishlists API scope

---

docs/api-docs/payments/payments-api-overview.md

Added `order_id=` to example payment methods URL

DEVDOCS-1214 Update URL param of payment methods GET request

---

docs/api-docs/catalog/currencies/currencies-overview.md

* Remove the table around the display / transactional screenshot as the screenshot actually shows both.

Remove Currency Screenshot Table

---

docs/stencil-docs/reference-docs/global-objects-and-properties.md

Adds `origin` to settings>request Stencil object

DEVDOCS-1238 added origin to stencil object for request settings

---

reference/json/BigCommerce_Store_Information_API.oas2.json

Adds graphql_storefront_api_enabled and wishlists_enabled to Store Information API features object

DEVDOCS-1239 adds graph ql to store info API plus other missing schema

---

reference/json/BigCommerce_Payments_API.oas2.json
reference/json/BigCommerce_Process_Payment_API.oas2.json

Adds GET Payment methods now surfaces stored PayPal accounts, and POST Create Payment accepts a token that is a paypal account.
Followed https://developer.bigcommerce.com/api-reference/store-management/orders/orders/updateanorder for a similar schema. See the Products array

Devdocs 1274

---

docs/api-docs/storefront/graphql/graphql-api-examples.md

* Adds example of retrieving a single product with Graph QL Storefront API

DEVDOCS-1302 Adds example to get a single product with GraphQL API

---

reference/json/BigCommerce_Customers_API.oas2.json

* Changed category_access.categories items type to integer instead of string
* Refactored to use definition references
* Added a CustomerGroupPost object and removed the ID parameter.

Update category_access.categories items type to int

---

docs/api-docs/storefront/graphql/graphql-api-overview.html
docs/api-docs/storefront/graphql/graphql-api-overview.md

Removes the distinction that Storefront tokens are non-JWT, as this is no longer the case

DEVDOCS-1294 Removes distinction that sf tokens are non-jwt

---

docs/stencil-docs/installing-stencil-cli/troubleshooting-your-setup.md

* Updated TR-300 Error in Documentation to give more information about the error as when we encountered it. It was very unclear and only after digging into the issues for stencil-cli did we find the root cause.
* See closed ticket https://github.com/bigcommerce/stencil-cli/issues/510 for the source of the information.

Updated TR-300 Error in Documentation

---

docs/api-docs/developers-guide-headless.md

* Removed the niche example of using admin email to redirect shoppers
* Added some generic options that weren't included before
* Listed Sites and Routes API as an option and flagged it as recommended

DEVDOCS-1175: Fix Headless Redirect Examples

---

reference/json/BigCommerce_Server_to_Server_Checkout_API.oas2.json

* The auth token and client id settings weren't available because no-security was set at the operation level. Removed that so that global security could take affect.

Remove Operation Level Security from S2S Checkout

---

docs/stencil-docs/reference-docs/handlebars-helpers-reference.md

This was resolved with DEVDOCS-1224, but now the comma has been re-added

Remove comma from ellipsis helper, update spelling

---

reference/json/BigCommerce_Catalog_API.oas2.json

* adds id query param to categories endpoint

adds id to query category params

---

reference/json/BigCommerce_Catalog_API.oas2.json
reference/json/BigCommerce_Channels_Listings_API.oas2.json
reference/json/BigCommerce_Orders_API.oas2.json

Somehow, it's not against the OpenAPI spec to have a type of "integer"
but enum values as strings. However, openapi-generator-cli can't
generate code for these schemas.
* Product condition is a string, not an integer.
* Listing states are explicitly strings.
* Order coupon discount types are integers, not strings.

Use correct types for given enum values

---

docs/api-docs/catalog/currencies/currencies-overview.md
docs/api-docs/catalog/currencies/how-currencies-work.md

* Removed References to Beta in Currency Docs

Remove References to Beta in Currency Docs

---

assets/html/graphql/playground.html

* Changed the URLs to use the dev-docs github pages paths
* Added some logic at the on playground.html that will cause token and endpoint to be added if on dev center.

Configure Playground for Use on Dev Center

---

docs/stencil-docs/storefront-customization/custom-templates.md

Add information to Stencil documentation about specifying front matter on custom page templates

DEVDOCS-1370: Add Section on Using Front Matter with Custom Templates

---

assets/js/playground_tabs.js
docs/api-docs/storefront/graphql/graphql-api-overview.md

* Added section to graphql overview for pagination
* Removed the customer query  tab (since it didn't work because of the ID)
* Replaced it with a tab for first three products to use in the graphql overview.

Add Pagination Example to GraphQL Overview

---

docs/stencil-docs/getting-started/about-stencil.md

* Removed the verbiage on removing Foundation and replacing it with another framework -- its not necessary
* Cleaned up verbiage in a few other spots and pulled some H3s out to H2s.

DEVDOCS-1384: Remove Verbiage on Swapping Foundation

---

docs/bigcommerce-for-wordpress/getting-started/supported-features.md

Move Shopper Wishlists from General Product Roadmap to BigCommerce for WordPress Supported features. Introduced with v.3.4.0: https://github.com/bigcommerce/bigcommerce-for-wordpress/releases/tag/3.4.0

Move Shopper Wishlists

---

docs/legacy/blueprint-themes/blueprint-template-syntax.md

Fix typo on /legacy/blueprint-themes/blueprint-template-syntax

remove otp typo in BP docs

---

docs/api-docs/cart-and-checkout/working-sf-apis.md

Updated the spelling of CORS within the following sentence: "_The URL should be served over https and be on the permanent URL; otherwise, it can cause **CORs** errors in the console._"
Now it reads "The URL should be served over https and be on the permanent URL; otherwise, it can cause **CORS** errors in the console."

Changing CORs to CORS

---

docs/api-docs/catalog/currencies/currencies-overview.md

* Added the following text to "Adding a Currency":
For instance, changing the default currency will not trigger price recalculation for the catalog. 
Additionally, changing the default currency will enable the newly assigned currency as transactional.

Add Note for Default Currency

---

docs/stencil-docs/installing-stencil-cli/stencil-cli-options-and-commands.md

* added a note to `stencil start` about --theme-editor and --theme-editor-port [port] being deprecated as of v1.23.1.

Stencil CLI Theme Editor Deprecated

---

docs/api-docs/storefront/graphql/graphql-api-overview.md

* Clarified that API is in open beta, and where to go for updates (changelog)
* Removed a lot of "enroll in the beta" verbiage since all stores are enabled
* Remove references to "simple token"
* Remove "channel ID 1 is the only valid Channel ID"
* Remove reference to community group
* Other tiny edits for clarity
ping @bigcommerce/dev-docs

Several clarfications related to GraphQL Storefront API

---

reference/BigCommerce_Process_Payment_API.oas2.yml

The description for the payment_method_id property in the request body for the Process Payment for an Order API does not make it clear what the source of the value should be. It is `id` from the Get Accepted Payment Methods API, but without reading additional documentation or examining the example requests, it may be confused with `method` from the Get Transactions API, or `code` or `name` from the Get All Payment Methods API.
* Appended  "and `id` from the Get Accepted Payment Methods API" to all descriptions of payment_method_id in the Process Payment for an Order reference.

Clarify payment_method_id description

---

docs/api-docs/getting-started/webhooks/webhook-events.md

* We've changed the response so that BC sends the `OrderId` as an integer. Updated documentation example of payload to reflect this change

Fix orderID in store/shipment/created webhook event to reflect integer

---

docs/stencil-docs/deploying-a-theme/troubleshooting-theme-uploads.md

* Updated TD-500 error meaning. Updated text: "The .zip file is larger than the 50MB limit; or the parsed JSON for templates exceeds the 1MB size limit."

Update TR-500 Error Meaning

---

docs/api-docs/getting-started/available-apis.md

* added a new section - "Deprecated BigCommerce APIs"

Add Deprecated API Endpoints

---

docs/api-docs/getting-started/available-apis.md

* Updated V2 `options` deprecated section: "In V3, options and modifiers are attached directly to the product. Use options and modifiers together to access the contents of the former V2 options response."
* Corrected a typo in "Once sunset, the endpoints will **no** longer be available."

Add Modifiers to V2 Options

---

docs/api-docs/getting-started/available-apis.md

Update Available APIs deprecations list to include V3 Channels `is_enabled` property

update available APIs deprecations

---

docs/api-docs/payments/payments-api-overview.md

* removed "Adyen" from the Hosted Provider section of the Payments API documentation

Remove Adyen from Payment Limitation

---

docs/legacy/blueprint-themes/blueprint-email-templates.md

* removed `%%GLOBAL_TrackingLinkList%%` from Available Variables in the Order Status Email Template.

Remove TrackingLinkList Variable

---

docs/api-docs/storefront/graphql/graphql-api-examples.md

* Where it was written `his`, it should be `this`

Typo fix at graphql-api-examples.md

---

docs/api-docs/cart-and-checkout/add-to-cart-url.md

* updated the example URL for the "Add product to cart and set coupon code" scenario. 
`https://{{domain}}/cart.php?action=add&product_id={{id}}&couponcode={{code}}`

Fix Common Usage URL Example

---

docs/api-docs/payments/payments-api-overview.md

* Adds Stripe V3 as a supported gateway for stored cards. Do not merge until June 1 as per ticket

DEVDOCS-1830 Adds Stripe V3. (Merge Jun 1)

---

docs/api-docs/catalog/products-overview.md

* Removes mention of Categories being a requirement for creating a new Product

Removes mention of category association begin a requirement for products

---

docs/api-docs/catalog/products-overview.md

Previous request referenced https://api.bigcommerce.com/stores/{{STORE_HASH}}/v3/catalog/summary, which is not the Category Tree.

Fix Category Tree Request

---

docs/api-docs/catalog/products-overview.md

Reverts DEVDOCS-1912 after receiving DM from Dymtro that he was mistaken about this change being rolled out yesterday 6/25

Revert "Removes mention of category association begin a requirement for products"

---

docs/api-docs/storefront/graphql/graphql-api-overview.md

Changed "For a a quick example..." to "For a quick example..."
Removed duplicate letter a from sentence under the _Querying Within a BigCommerce Storefront_ section.

removed duplicate letter a

---

docs/api-docs/catalog/currencies/currencies-overview.md

Fix spelling of the word analytics under the FAQ: Will my analytics show in the transactional or display currency?
Change the sentence from "Currently it does not break down anayltics by currency." to "Currently it does not break down analytics by currency."
Fixed spelling error

Fixed spelling error

---

docs/api-docs/store-management/shipping/shipping-provider-api.md

Changed "Exampe Request with Empty Object" to "Example Request with Empty Object"
fixed typo

Fixed typo

---

docs/api-docs/storefront/graphql/graphql-api-examples.md

Removed the following line because it appears twice under the code sample for Get a Customer's Details.
**[Try it in GraphQL Playground](https://developer.bigcommerce.com/graphqlplayground_tab=customerDetails)**
Removed duplicate text

Removed duplicate text

---

docs/api-docs/getting-started/available-apis.md

The Markdown formatting for Product Videos had an extra line in it which made it appear incorrectly. I put all the text on one line to fix the issue.
link for Product Videos

Fixed Markdown formatting

---

docs/api-docs/payments/payments-api-overview.md

My understanding from the ticket is to add MyVirtualMerchant to the list of stored cards gateways. I asked Kyle Nowakowski to confirm that no other changes are needed.
MyVirtualMerchant is now available to process payments and the documentation should be updated to let our customers know.

Added MyVirtualMerchant to stored cards list

---

docs/api-docs/getting-started/webhooks/setting-up-webhooks.md

All updates have been added except for following items I need help with:
1. The documentation includes a Postman collection with all the requests, however, the description for one of the key:value pairs is incorrect. For X-Auth-Token, the value says "client_secret", it should say "{{Access_token}} in the requests. See the attached screenshot. Can the collection be updated?
2. How do you obtain the webhooks ID? It is mentioned near the end of the tutorial to delete the webhook but how do you know what the webhooks ID is? I would like to add this information.
3. How do you send a custom response in res.send? I tried changing the text but did not see the custom response. I don't need to add this information but I wasn't able to figure it out.
4. This last item is more of a comment that we …

Updated Webhooks Tutorial for clarity

---

docs/stencil-docs/installing-stencil-cli/live-previewing-a-theme.md

* Fixed anchor on Stencil CLI installation docs page
https://developer.bigcommerce.com/stencil-docs/installing-stencil-cli/live-previewing-a-theme#serving-live-preview doesn't scroll to the section, but https://developer.bigcommerce.com/stencil-docs/installing-stencil-cli/live-previewing-a-theme#serving-a-live-preview does

Fix anchor on Stencil CLI installation docs page

---

docs/stencil-docs/installing-stencil-cli/stencil-cli-options-and-commands.md

This change is one of many changes for DEVDOCS-1985 in order to remove legacy information and fix typos.
Removed unnecessary colons

Made small editorial changes

---

docs/stencil-docs/deploying-a-theme/naming-your-theme.md

A link was missing a for "Preparing Thumbnail Images" so I added it. 
This link is in the Preparing a variation's thumbnails section.
Fixed link

Fixed missing link

---

docs/stencil-docs/javascript-and-event-hooks/dynamic-content-rendering.md

Adding back in "Pixel Union Merchant theme".  Brandy Simek did not want this information removed because it was a customer tutorial. Sorry this was not clear in the initial PR.
Adding back in Pixel Union Merchant Theme. Brandy said the following, "i would not remove that. that was a customer-written tutorial"

This information should not have been removed

---

docs/bigcommerce-for-wordpress/getting-started/supported-features.md

Product Pick Lists feature is now supported. This item was moved to the supported BigCommerce for Wordpress Supported Features list.
I am wondering why this item has an asterisk in the name. What does it mean? Product Pick Lists and Bundled * Products
Is it "Page Builder Plugins Support" or "Page Builder Plugin Support". I am not sure.
Moved Product Pick list to the supported features list.
Possible editorial change for Page Builder Plugins Support

Moved item to supported features list

---

docs/stencil-docs/storefront-customization/using-front-matter.md

Front-matter block was not consistent throughout this page so I changed all instances to "front-matter block" instead of "front matter block"
Removed YAML Syntax section. Austin said it was not needed.
Added a link for the reference section under Reading the Handlebars
Fixed the broken link for Front Matter Attributes Reference and Front Matter Reference
see list above

Updated text and links

---

docs/stencil-docs/storefront-customization/custom-templates.md

There were two places where the text was gray and not black, so I changed it to be consistent.
Updated link for Applying a Custom Template (in two places)
See list of changes above

Updated text in Custom-templates.md

---

docs/stencil-docs/localization/multi-language-checkout.md

Under Adding Your Own Translation Values, the Internationalization section link needed to go to a different section
updated Internationalization section link

fixed link in multi-language-checkout.md

---

docs/stencil-docs/developing-further/google-analytics-enhanced-ecommerce.md

Needed to add a link to _Cornerstone theme installed_ as the other prerequisites are all links
https://developer.bigcommerce.com/stencil-docs/developing-further/updates/google-analytics-enhanced-ecommerce
Ticket (DEVDOCS-1985) is closed but I couldn't find an open ticket to put this under.  All prerequisites are links now

Added a link

---

docs/api-docs/customers/passwordless-login.md

I also fixed some section headings.
I resolved comments given by Austin in PR-513.
Luis Sanchez said the following:
It means the customer requested a sign in link, but because it's been flagged as "reset password on next login", they will receive instead a reset password email

Update passwordless login per review

---

docs/api-docs/orders/orders-api-overview.md

Updated per DEVDOCS-2069, added clarification to the _Create an order shipment_ section
Fixed the passive voice in the sentence and added the following:
You can create multiple shipments for an order by specifying a subset of products or product quantities in each POST request.

Updated Orders-api-overview.md

---

docs/api-docs/getting-started/available-apis.md

* For each deprecated API, link to the newest API that should be used instead
* Add V3 Redirects to list of available V3 APIs

Link to the newest API in the deprecation section, add V3 Redirects to available APIs

---

docs/api-docs/getting-started/available-apis.md

* Removed some `</div>`s near the end of the file; looks like they've been there a while and only started causing problems when the `<div>` for the OTP was added recently.

DEVDOCS-2099: Fix Broken API Reference

---

docs/api-docs/catalog/pricing-order-operation.md

After reviewing the changes, I found that product was listed twice after "with" was removed.  
"Product product pick list" is now "Product pick list"

Fix pricing-order-operation

---

docs/stencil-docs/deploying-a-theme/bundling-and-pushing.md

I removed one last occurrence of jspm in dev docs.  This is the last one I found when did a search.

Update bundling and pushing

---

docs/stencil-docs/reference-docs/handlebars-helpers-reference.md

Variables helpers (assignVar, getVar, decrementVar, incrementVar) currently have invalid examples. This commit fixes these examples.
With the current example, the console returns "assignVar helper key must be a string". The updated example is valid.
* Example code for assignVar
* Example code for getVar
* Example code for decrementVar
* Example code for incrementVar

Fix examples in Variables helpers

---

docs/api-docs/getting-started/webhooks/about-webhooks.md

* Updated webhooks retries intervals.

DEVDOCS-2133: Update Webhooks Retries Info

---

docs/api-docs/cart-and-checkout/cart-and-checkout-overview.md

* Removed mention of needing OAuth scopes for Storefront APIs; they require no scopes, as they are authenticated by the storefront session cookie.

Remove mention of OAuth scopes for storefront APIs

---

docs/stencil-docs/storefront-customization/theme-assets.md

* Remove mention of Akamai Image Manager optimizations as it's [no longer a thing.](https://developer.bigcommerce.com/changelog#posts/per-device-image-resizing-based-on-user-agent-has-been-disabled-use-srcset)
FYI @chrisboulton

Remove mention of Akamai image manager

---

docs/stencil-docs/installing-stencil-cli/installing-stencil.md

Updating to use node 10.17
* Updating node installation instructions to reference 10.17 as running under 10.16 returns `Error: You are running an unsupported version of node. Please upgrade to ^10.17 || ^12`.
* Tested on Mac, untested on windows (But I assume 10.16 isn't supported there either).
* On a basic `stencil init` check 10.17 appears to work fine. No idea if it works beyond that, I used 12 when the error gave me the suggestion to.
* It would probably be better to suggest installing the **newest possible version** for each platform rather than the oldest if there's no technical reasons to suggest the older version. 12.19 worked fine on Mac for my needs; but I'm not clear on the windows support there, and it seemed easier to keep this PR to the 10.17 branch to avoid a big version …

Updating Node Version

---

docs/stencil-docs/installing-stencil-cli/installing-stencil.md

* Removed install npm and nodejs step since nvm will install both when you run `nvm install`. 
* Added links to stencil cli and nvm readme with instructions on getting latest info for both.

DEVDOCS-2282: Fix Linux Install Instructions

---

docs/stencil-docs/reference-docs/handlebars-helpers-reference.md

* removed links to github from headers

DEVDOCS-2274: Removed links from helper headers (h3)

---

docs/api-docs/storefront/graphql/graphql-api-overview.md

* Added `credentials: 'same-origin'` to `fetch` request examples.
* Changed `fetch` request code blocks to `js` for clarity, simplicity.
* Added callout about `credentials same-origin` being required even for stencil themes.

DEVDOCS-2324: Include Credentials Same-Origin

---

docs/stencil-docs/reference-docs/common-objects.md

* Remove `qty_in_cart` from common product card model.

Remove qty_in_cart from stencil context docs

---

assets/js/playground_tabs.js

* Added Customer Login example to GraphQL playground (now that bugs are fixed with it)
Depends on https://github.com/bigcommerce/storefront/pull/1019 making it to production.

Add customer login example to docs

---

docs/api-docs/channels/channels-extending-existing.md

"app config object" pointed to `#sample-channel-app-configuration`, changed to `#sample-configuration`

Fix #sample-configuration anchor

---

docs/stencil-docs/javascript-and-event-hooks/adding-javascript.md

Replace the single forward slash(/) path with a double backward-slash(\\) path for Windows machine, fixes the unsuccessful issue on the OS
* added a commented line of code meant to be used on a Windows machine for local development
* for the local changes to work on cloud store, the path separator has to be reverted back to the forward slash
* the changes are only for local development, preview, and testing

Fix the custom template JS mapping path-separator slashes

---

docs/api-docs/getting-started/webhooks/about-webhooks.md

https://sslcheck.globalsign.com no longer exists.
The SSL checker on GlobalSign's site now leads to https://globalsign.ssllabs.com/
* Fixed broken SSL checker link

Update GlobalSign SSL Checker link

---

docs/stencil-docs/reference-docs/handlebars-helpers-reference.md

* Fixed "JavaScript" spelling error

DEVDOCS-2579: Fix spelling error

---

assets/js/playground_tabs.js

* [DEVDOCS-2544](https://jira.bigcommerce.com/browse/DEVDOCS-2544)
* [DEVDOCS-2450](https://jira.bigcommerce.com/browse/DEVDOCS-2450)
* [DEVDOCS-2506](https://jira.bigcommerce.com/browse/DEVDOCS-2506)
* 
* Added code comments to graphql playground query tabs that instruct users to navigate to playground from the control panel or make queries agaisnt buybutton.store (playground will not work otherwise). 
* Also added comment about queries not working against stores in maintenance mode and cross-origin login won't work in chrome incognito or safari.

Graphql playground clarification

---

docs/api-docs/store-management/shipping/shipping-provider-api.md

Added content to clarify the required values that external developers should send BC in order for us to create a shipping provider configuration for them.
Specifically, added the following point to the **Sign-up** section of the **Shipping Providers** [API Docs](https://developer.bigcommerce.com/api-docs/providers/shipping).
> - Your service URLs (see below)
External developers were emailing us requesting a shipping provider config to be set up without including their service URLs, requiring BC to email them back requesting this information before we could complete creation of their shipping provider configuration.

docs(shipping): DEVDOCS-2618 Update Shipping Providers API Docs

---

docs/api-docs/storefront/graphql/graphql-api-overview.md

* Removed an `<a>` tag with a `#complexity-limits` ID to stop it from superseding the autogenerated anchor to the Complexity Limits subheading later in the page

Remove duplicate complexity-limits anchor

---

docs/api-docs/orders/order-refunds.md

Within the [Order Refunds API Docs](https://developer.bigcommerce.com/api-docs/store-management/order-refunds#faq) FAQ section, updated the copy of the below question:
> Will this trigger an email to the merchant?
To instead say:
>Will this trigger an email to the shopper?
The previous copy was not representative of functionality.
Revert this PR.
ping @uwikaiddi @bigcommerce/orders

docs(orders): DEVDOCS-2742 Update Orders Refunds API Docs

---

docs/api-docs/storefront/widgets/widgets-overview.md

* Remove the mention of default global regions from Widgets API Overview. What regions are available by default is determined by the theme.

DEVDOCS-2782: removed default global region

---

docs/api-docs/provider-apis/tax/overview.md

Note: Created a TAX ticket for internal team tracking purposes.
Improved partner sandbox description and introduced a link to creating a partner sandbox store on the following page https://developer.bigcommerce.com/api-docs/providers/tax.
Partners were creating trial stores for integration testing purposes. The trial store would then expire and they would be blocked from testing their integration until they figured out how to create a partner sandbox store. 
Revert this PR.
ping @bigcommerce/shipping @uwikaiddi

docs(tax): TAX-1051 Improve partner sandbox store description

---

docs/api-docs/channels/building-channel-apps.md
docs/api-docs/channels/channel-app-requirements.md
docs/api-docs/channels/channels-extending-existing.md

* Added lines about config_meta.app.id being optional for create channel requests, but required for select partners.

DEVDOCS-2670: Update Config Meta Usage

---

docs/api-docs/getting-started/webhooks/about-webhooks.md
docs/api-docs/getting-started/webhooks/setting-up-webhooks.md

* Added notes about custom ports not being supported. 
* Re-wrote and updated webhook tutorial to use the ngrok npm package for simplicity. 
I tested the new instruction for the webhooks tutorial on my windows machine using git bash. They worked nicely.

DEVDOCS-2754: Add Webhook Port Limitations

---

docs/api-docs/getting-started/best-practices.md

* Improve verbiage related to Enterprise API rate limits to better describe what "unlimited" means.

Improve verbiage related to Enterprise API rate limits

---

docs/api-docs/catalog/products-overview.md
docs/stencil-docs/installing-stencil-cli/live-previewing-a-theme.md

* Update anchor link in TOC as requested
* Found and updated several other URLs that were broken

Devdocs 2975 - Wrong anchor link

---

docs/api-docs/provider-apis/tax/overview.md

- Refined the store profile component of the Testing section to reference only the "Default Country" field. 
- Also some minor punctuation updates.
This came up recently since a tax provider needed to reference this list of requirements.
ping @uwikaiddi @bigcommerce/shipping

Update store profile requirement description in Tax Provider API > Testing

---

assets/js/playground_tabs.js

* Update the "extended product" example to express all `productOptions` fields to describe the full feature set of the product options resources.

Add all productOptions fields to example

---

docs/stencil-docs/storefront-customization/custom-sass-functions.md

Docs incorrectly state that custom sass files should be imported to theme.css
as opposed to theme.scss

Update incorrect filename reference

---

docs/api-docs/getting-started/webhooks/webhook-events.md

https://jira.bigcommerce.com/browse/DEVDOCS-3315
* added summary for  store/order/transaction/created and store/order/transaction/updated
* added schema summary for store/order/transaction/created and store/order/transaction/updated

DEVDOCS-3315: add webhook events for transactions

---

docs/api-docs/payments/payments-api-overview.md

Update Payments API docs to clarify what "verification_value" is.
verification_value isn't the last_four, but rather the CVC
ping @bigcommerce/payments

DEVDOCS-3468: Update Payments API docs to clarify what "verification_value" is

---

docs/api-docs/cart-and-checkout/embedded-checkout-tutorial.md
docs/api-docs/customers/customer-login-api.md

Add "channel_id" to the Payload Fields reference on this page: 
Used the following description: "Optional field containing the channel_id corresponding to a headless storefront."

DEVDOCS-3719 Add channel_id to the payload fields reference

---

docs/api-docs/storefront/graphql/graphql-api-overview.md
docs/stencil-docs/reference-docs/global-objects-and-properties.md

* Note that products.new, products.top_sellers, and products.featured return 10 products
* Note that GQL image queries return 10 images

Devdocs 3659

---

docs/legacy/v2-products/v2-v3.md

One additional change for DEVDOCS-3665 (a continuation of [PR 1434](https://github.com/bigcommerce/dev-docs/pull/1434))

DEVDOCS-3665: additional change

---

docs/stencil-docs/reference-docs/front-matter-reference.md

* correct link per ticket
* table & code block formatting

DEVDOCS-3808: broken link to gql-playground

---

docs/api-docs/getting-started/best-practices.md

`getHeaders()` no longer returns `X-Rate-Limit-Time-Window-Seconds` but instead it returns `X-Rate-Limit-Time-Window-Ms`
* `X-Rate-Limit-Time-Window-Seconds` but instead it returns `X-Rate-Limit-Time-Window-Ms`

DEVDOCS-4090: Update best-practise guide

---

docs/api-docs/channels/channels-quick-start.md
docs/api-docs/channels/channels-storefront-tutorial.md

Relates to https://github.com/bigcommerce/api-specs/pull/748
* Update DevDocs so they no longer reference the deprecated `config_meta.app.sections` for management of UI Sections.  Those references have been replaced with references to the new Channel Menus API. [CHP-7375](https://bigcommercecloud.atlassian.net/browse/CHP-7379).
(PR description updated by @slsriehl)

DEVDOCS-3979 / DEVDOCS-3779: Update Dev Docs to replace `config_meta` w /channel-menus

---

docs/api-docs/channels/channels-quick-start.md
docs/api-docs/channels/channels-storefront-tutorial.md

* Update Dev Docs so they no longer reference the deprecated `config_meta.app.sections` for management of UI Sections.  Those references have been replaced with references to the new Channel Menus API. CHP-7375
* Updated with Ashley's changes
* Modified 2 files
Co-authored-by: Sarah Riehl <sarah.riehl@bigcommerce.com>
Co-authored-by: Preston Huth <preston.huth@bigcommerce.com>

Staging to Master

---

docs/api-docs/apps/guide/apps-04-devloper-portal.md
docs/api-docs/apps/guide/apps-13-publishing.md
docs/api-docs/getting-started/authentication.md
docs/api-docs/getting-started/rest-api-authentication.md
docs/msf/msf-app-compatibility.md

* Updates re Dev Portal and MSF app compatibility inputs. Docs include:
* managing apps in the dev portal
* apps publishing guide
* Additionally, relocated info on creating app API accounts from auth to managing apps in the dev portal (linked)
* Also relocated the best version of the x-auth-client header deprecation callout

DEVDOCS-3876 Update app guide with MSF app profile options

---

docs/stencil-docs/localization/multi-language-checkout.md
toc.json

Devdocs 4298 fix broken links in multi language checkout

---

docs/api-docs/tax/tax-properties.md

1) Removed use case about multiple tax providers and transitioning between tax providers 
2) Reworded explanations. “Tax codes” has been a well-defined concept in the tax field. The doc now uses a different language to describe tax properties.
3) Highlighted the primary use case (each input can have a different value and hence you can easily capture things like alcohol composition).

DEVDOCS-4384: [edit] remove incorrect use case, Tax Properties API

---

pull_request_template.md
pull_request_template_CODEOWNER.md

* remove markdown link bodies that now auto-populate
* update codeowner publication template to reflect current workflow
* This doesn't complete DEVDOCS-3351
* See parallel [PR 957](https://github.com/bigcommerce/api-specs/pull/957) in the api-specs repo
[DEVDOCS-3351]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-3351?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-3351: [internal] Update PR templates

---

docs/api-docs/partner/pos/foundation-guide.md

This section was moved to the POS Foundation readme file
[DEVDOCS-4312](https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4312)

DEVDOCS-4312: [remove] POS Foundation, move expansion resources to GitHub

---

toc.json

* add `Beta Features` section to ToC
* add absolute link to Promotions API beta narrative docs
* add absolute link to Customer Segmentation API beta narrative docs
* see [api-specs PR 973](https://github.com/bigcommerce/api-specs/pull/973)
[DEVDOCS-4047]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4047?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEVDOCS-4433]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4433?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-4047, DEVDOCS-4433: [navigation] Promotions & Customer Segmentation API beta, add to toc

---

docs/api-docs/apps/guide/apps-01-introduction.md
docs/api-docs/apps/guide/apps-04-devloper-portal.md
docs/api-docs/apps/guide/apps-05-oauth.md
docs/api-docs/apps/guide/apps-09-ui.md
docs/api-docs/apps/guide/apps-11-best-practices.md
docs/api-docs/apps/guide/apps-12-requirements.md
docs/api-docs/apps/guide/apps-13-publishing.md
docs/api-docs/cart-and-checkout/channels-sites-routes.md
docs/api-docs/channels/building-channel-apps.md
docs/api-docs/channels/channels-overview.md
docs/api-docs/provider-apis/tax/overview.md
docs/api-docs/store-management/shipping/shipping-provider-api.md
docs/stencil-docs/customizing-checkout/checkout-confirmation-injection.md
docs/stencil-docs/page-builder/third-party-widgets.md

change to App Marketplace
[DEVDOCS-4428]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4428?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-4428: [update] Standardize references to the App Marketplace

---

docs/api-docs/orders/orders-api-overview.md

* Add note that identifies known stock change behaviors when `awaiting fulfillment` orders are edited manually and 
* Linked to KB article for more info
* Apply MD styleguide to docs
[DEVDOCS-4118]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4118?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-4118 [maint.] Update stock changes to manual edit orders

---

docs/stencil-docs/reference-docs/handlebars-helpers-reference.md

Specify whether the for loop ending number is inclusive or exclusive.
I'm not partial on how it should be specified or where, it might work better in the description where it can be explained better. But, since both inclusive and exclusive forloops are common across languages, it should be specified in some way other than relying on the example.
* Specify whether the for loop ending number is inclusive or exclusive.

DEVDOCS-4558: [value add] Handlebars reference, specify inclusivity of forloop end number

---

docs/stencil-docs/reference-docs/handlebars-helpers-reference.md

Specify whether the for loop ending number is inclusive or exclusive.
[DEVDOCS-4558]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4558?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-4558: [update] Handlebars helpers, specify inclusivity of forloop end number

---

docs/api-docs/cart-and-checkout/open-source-checkout.md
docs/stencil-docs/reference-docs/handlebars-helpers-reference.md
docs/stencil-docs/storefront-customization/early-hints.md

* add new page for Early Hints
* update {{cdn}} Handlebars helpers page with Early Hint info
[DEVDOCS-4543]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4543?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-4543 Early Hints

---

docs/stencil-docs/installing-stencil-cli/stencil-cli-options-and-commands.md

* Remove test flag from stencil-cli-options-and-commands
* Add channelId flag to stencil-cli-options-and-commands
* Add timeout flag to stencil-cli-options-and-commands
Relating to #1691 
[DEVDOCS-4655]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4655?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

#1691 Remove test flag on Stencil Start command && Add channelId and timeout flags

---

assets/csv/tracking_carrier_values.csv

* escape comma in carrier name to make CSV searchable
[DEVDOCS-4602]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4602?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-4602: [fix] [sprawl] Escape comma in shipping carrier tracking values

---

docs/stencil-docs/installing-stencil-cli/stencil-cli-options-and-commands.md

added --no-verbose and --verbose to stencil start
[DEVDOCS-4649]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4649?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-4649: [update] Stencil CLI logging options

---

docs/api-docs/cart-and-checkout/checkout-sdk.md

* Link with all lowercase leads to a 404 page. Updated link to correct github page.
[DEVDOCS-4665]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4665?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Update checkout-sdk.md - DEVDOCS-4665

---

docs/api-docs/cart-and-checkout/checkout-sdk.md

* Link with all lowercase leads to a 404 page. Updated link to correct github page.
See PR #1699
[DEVDOCS-4665]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4665?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-4665: [fix] Update Checkout SDK link

---

docs/api-docs/store-management/shipping/shipping-provider-api.md

Added custom form fields to Shipping Provider API
This PR is related to [PR 1038](https://github.com/bigcommerce/api-specs/pull/1038)
[DEVDOCS-4560]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4560?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-4560: [add] Shipping Provider, add form_fields to destination

---

docs/api-docs/getting-started/deprecations-and-sunsets.md

* remove Get widgets by search
* [api-specs 1097](https://github.com/bigcommerce/api-specs/pull/1097)
* [redirects 164](https://github.com/bigcommerce-labs/next-dev-center-prototype/pull/164)
[DEVDOCS-4388]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4388?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-4388: [deprecate] Widgets, Get widgets by search

---

docs/api-docs/storefront/graphql/graphql-api-overview.md

Added note about revoking only compromised tokens
This PR is related to [PR 1115](https://github.com/bigcommerce/api-specs/pull/1115) (api doc)
[DEVDOCS-4668]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4668?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-4668: [update] GraphQL overview, clarify intent of Revoke a token endpoint

---

docs/api-docs/getting-started/deprecations-and-sunsets.md

* Update the intro
* Add product tools table
* Add Google AMP to the table
[DEVDOCS-4703]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4703?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-4703: [update] Add Google AMP to the deprecations list

---

docs/stencil-docs/reference-docs/handlebars-helpers-reference.md

* Handlebars Helpers Reference for strReplace
[DEVDOCS-4693]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4693?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEVDOCS-4711]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4711?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-4711: [external] Handlebars reference, add strReplace helper

---

docs/stencil-docs/reference-docs/handlebars-helpers-reference.md

* Refine external PR that adds previously-undocumented strReplace helper
* #1723 
[DEVDOCS-4711]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4711?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-4711: [update] Handlebars reference, add strReplace helper

---

docs/api-docs/payments/payments-api-overview.md

Added a sentence about the payments API not supporting the Test Payment Gateway
[DEVDOCS-4666]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4666?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-4666: [update] Payments API, clarify no test payment gateway support

---

docs/api-docs/getting-started/webhooks/webhook-events.md

Reversed the definition of absolute and relative
This is an outstanding change from DEVDOCS-3453.
[DEVDOCS-4770]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4770?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-4770: [update] Webhooks, reverse SKU inventory method definitions

---

.eslintrc.json
package-lock.json
package.json

* **Important:** This PR bumps `engines.node` in `package.json` from `>= 0.10.0` to `>= 14.0.0`. There might be some historical `dev-docs` team reason that this shouldn't be done, that I'm not aware of. Let's avoid merging until we confirm nothing downstream will break because of this change.
* Adds [https://github.com/mdx-js/eslint-mdx](https://github.com/mdx-js/eslint-mdx) for basic MDX linting
N/A

(no ticket): [tools] add mdx linter, bump node to work with linter

---

docs/api-docs/apps/guide/apps-01-introduction.mdx
docs/api-docs/apps/guide/apps-02-types.mdx
docs/api-docs/apps/guide/apps-03-developing.mdx
docs/api-docs/apps/guide/apps-05-oauth.mdx
docs/api-docs/apps/guide/apps-06-callbacks.mdx
docs/api-docs/apps/guide/apps-07-users.mdx
docs/api-docs/apps/guide/apps-08-events.mdx
docs/api-docs/apps/guide/apps-09-ui.mdx
docs/api-docs/apps/guide/apps-10-buttons.mdx
docs/api-docs/apps/guide/apps-11-best-practices.mdx
docs/api-docs/apps/guide/apps-12-requirements.mdx
docs/api-docs/apps/guide/apps-13-publishing.mdx
docs/api-docs/channels/channels-toolkit-reference.mdx
docs/api-docs/partner/dev-portal-overview.mdx
docs/stencil-docs/configure-store-design-ui/defining-global-styles.mdx
docs/stencil-docs/getting-started/stencil-technology-stack.mdx
docs/stencil-docs/getting-started/transitioning-to-stencil.mdx
docs/stencil-docs/localization/localization-tutorial.mdx
docs/stencil-docs/localization/translation-keys.mdx
docs/stencil-docs/storefront-customization/custom-templates.mdx
docs/stencil-docs/storefront-customization/theme-accessibility.mdx
docs/stencil-docs/storefront-customization/theme-assets.mdx
docs/stencil-docs/storefront-customization/using-custom-fonts-and-icons.mdx

* The GitHub action has given notices about URLs starting with `//` not working. I recall this was a workaround to prevent embedded links in Stoplight, but they don't currently work.

[hachachacha] Updated broken Figma and Youtube URLs

---

docs/api-docs/store-management/shipping/shipping-provider-api.mdx

- Remove x-auth-token from the example headers being sent to our shipping provider endpoints. This is not actually being sent.
ping @bigcommerce/shipping @bc-andreadao 
[DEVDOCS-4828]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4828?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(shipping): SHIPPING-700 Remove unused x-auth-token header

---

docs/api-docs/apps/apps-quick-start.mdx
docs/api-docs/partner/pos/foundation-guide.mdx
docs/api-docs/partner/subscriptions/foundation-guide.mdx
docs/stencil-docs/installing-stencil-cli/installing-stencil.mdx
docs/stencil-docs/installing-stencil-cli/stencil-cli-options-and-commands.mdx
docs/stencil-docs/installing-stencil-cli/troubleshooting-your-setup.mdx

Changed node version to 18.15.0
Added warning about the deprecation of node-sass
Here is a summary of my changes.
1. Updated node version from 14.20.0 to 18.15.0 in the following files:
- apps-quick-start.mdx
- /pos/foundation-guide.mdx
- /subscriptions/foundation-guide.mdx
-  installing-stencil.mdx
2. Added a warning message to the following files:
-  installing-stencil.mdx
-  stencil-cli-options-and-commands.mdx
-  troubleshooting-your-setup.mdx
3. Added instructions on how to update your system in the following file:
-  troubleshooting-your-setup.mdx

DEVDOCS-4761:[update] Add warning and update node version

---

docs/api-docs/apps/apps-quick-start.mdx
docs/api-docs/partner/pos/foundation-guide.mdx
docs/api-docs/partner/subscriptions/foundation-guide.mdx
docs/stencil-docs/installing-stencil-cli/installing-stencil.mdx
docs/stencil-docs/installing-stencil-cli/stencil-cli-options-and-commands.mdx
docs/stencil-docs/installing-stencil-cli/troubleshooting-your-setup.mdx

Changed node version to 18.15.0
Added warning about the deprecation of node-sass
Here is a summary of my changes.
1. Updated node version from 14.20.0 to 18.15.0 in the following files:
- apps-quick-start.mdx
- /pos/foundation-guide.mdx
- /subscriptions/foundation-guide.mdx
-  installing-stencil.mdx
2. Added a warning message to the following files:
-  installing-stencil.mdx
-  stencil-cli-options-and-commands.mdx
-  troubleshooting-your-setup.mdx
3. Added instructions on how to update your system in the following file:
-  troubleshooting-your-setup.mdx

DEVDOCS-4761: Stencil CLI 7x release with node 18 support

---

docs/api-docs/apps/guide/apps-11-best-practices.mdx

[DEVDOCS-3804]: Removed section that says: "BigCommerce limits concurrent requests to most endpoints to three. The endpoints specified below enjoy an increased limit."
[DEVDOCS-3804]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-3804?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-3804: [remove] Apps Guide, remove section about concurrent request limits

---

docs/api-docs/getting-started/deprecations-and-sunsets.mdx

* Add pages v2 to the list of deprecated APIs and endpoints
* Move the version number after the name of the API to match the newer references elsewhere
[DEVDOCS-3395]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-3395?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-3395: [deprecate] Deprecations + Sunsets, add Pages V2

---

docs/api-docs/getting-started/deprecations-and-sunsets.mdx

[DEVDOCS-4786](https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4786)
Added Get Events to the list of deprecated APIs
[DEVDOCS-4786]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4786?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-4786: [update] hook/events

---

.github/CODEOWNERS
.github/PULL_REQUEST_TEMPLATE/publication_pr_template.md
.github/PULL_REQUEST_TEMPLATE/pull_request_template.md
pull_request_template.md

* Restore PR template
* Make the team codeowner
ping @bigcommerce/dev-docs-team

(no ticket): [revise] add PR template, change codeowners

---

docs/api-docs/store-logs/store-logs.mdx

Document date_created filter on store logs API.
* Add filter for created by value
Related ticket: [ANA-3964](https://bigcommercecloud.atlassian.net/browse/ANA-3964)
[DEVDOCS-4499]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4499?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ANA-3964]: https://bigcommercecloud.atlassian.net/browse/ANA-3964?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[DEVDOCS:4499] [new] System Logs - Get System Logs, include Date Created filter info

---

docs/api-docs/webhooks/webhook-events.mdx

Renamed `store/variant/metafield` to `store/product/variant/metafield`
ping {names}
[DEVDOCS-4922]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4922?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-4922: [update] Webhook Events, rename store/variant/metafield

---

docs/api-docs/catalog/price-list-overview.mdx

* Add webhook information for price lists
* Add webhook link to webhooks segment
ping {names}
[DEVDOCS-5115]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5115?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5115: [revise] Price Lists, Add webhook notes to price lists overview

---

docs/api-docs/webhooks/webhook-events.mdx

Removed duplicate inventory sections in the Webhooks Events article.
ping {names}
[DEVDOCS-4922]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4922?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-4922: [revise] cleanup webhook events

---

docs/stencil-docs/storefront-customization/using-front-matter.mdx

It is possible to use front matter in custom templates. See [GitHub issue 1925](https://github.com/bigcommerce/dev-docs/issues/1925) and [Slack conversation](https://bigcommerce.slack.com/archives/CCSUP1W1J/p1687362456478229).
ping {names}
[DEVDOCS-5105]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5105?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEVDOCS-4951]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4951?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5105: [update] Update using-front-matter.mdx

---

docs/api-docs/webhooks/webhook-events.mdx

updated hash definition
ping {names}
[DEVDOCS-5107]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5107?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5107: [update] hash definition

---

docs/api-docs/cart-and-checkout/cart-and-checkout-overview.mdx

Remove includes statement for "Log checkout details to the console" example.
I tested the example and it still works fine.
See slack conversation: https://bigcommerce.slack.com/archives/C0WC9CSJX/p1688674131693349
ping {names}
[DEVDOCS-5158]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5158?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5158: [revise] remove includes statement

---

docs/stencil-docs/page-builder/wallet-buttons.mdx

Added a new section for cornerstone themes below version 6.7
ping {names}
[DEVDOCS-5190]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5190?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5190: [update] Wallet Buttons, support themes <6.7

---

docs/stencil-docs/reference-docs/common-objects.mdx

* Document `has_options` behavior for products that are out of stock, including options
ping {names}
[DEVDOCS-4799]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4799?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-4799 [revise] Stencil Docs, Common Objects `has_options` description update

---

docs/api-docs/store-management/shipping/shipping-provider-api.mdx

* Add new section explaining how to setup carrier configurations when using the Shipping Provider API.
* Provide relevant examples.
ping @bigcommerce/team-shipping @bc-andreadao 
[DEVDOCS-5220]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5220?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5220 [feat]: Update Shipping Provider API how-to guide on carrier configurations

---

docs/legacy/v2-catalog-products/v2-products.mdx

- Fix links to legacy docs
This PR fixes a mistake in[ PR 2032](https://github.com/bigcommerce/dev-docs/pull/2032)
[DEVDOCS-5026]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5026?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5026 [update]: links to legacy docs

---

docs/api-docs/getting-started/making-requests.mdx

- Add seconds to UTC timestamp description
This PR relates to [PR 1403](https://github.com/bigcommerce/api-specs/pull/1403)
[DEVDOCS-4701]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4701?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-4701 [update]: GQL Storefront API, update UTC timestamp description

---

docs/api-docs/channels/channel-webhooks.mdx

Added the following channel webhooks
* store/channel/{channel_id}/settings/site/checkoutUrl/updated
* store/channel/{channel_id}/settings/site/checkoutUrl/deleted
ping {names}
[DEVDOCS-4999]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4999?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-4999: [update] Added sites webhooks

---

docs/msf/msf-api-guide.mdx

Replace `site_id` with `channel_id` for Widgets API (Create a Widget Template) in msf-api-guide.mdx
Changed  `site_id` with `channel_id` and made minor updates to related description.
* 
ping {names}
[DEVDOCS-4795]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4795?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-4795: replace site_id with channel_id for widgets

---

docs/api-docs/getting-started/rest-api-authentication.mdx
docs/api-docs/users/overview.mdx

* Separate account scopes from store scopes
* Add link on Users Overview to the account level OAuth scopes
* Deduplicate a repeated scope
ping {names}
[DEVDOCS-4868]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4868?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

(no ticket): [update] Guide to API Accounts, add OAuth scopes

---

docs/stencil-docs/reference-docs/handlebars-helpers-reference.mdx

Reverse helper currently doesn't support array's type. Our documentation is correct, but the link goes to the old codebase, which is not fully correct (currently it says that supports string and arrays, but actually only strings are supported) and makes [confusion](https://github.com/bigcommerce/paper-handlebars/issues/292) 
Updated reverse helper link to our codebase
ping @bigcommerce/dev-docs @bigcommerce/team-storefront @bc-evan-johnson

[Stencil] Update handlebars reverse helper link

---

docs/api-docs/webhooks/about-webhooks.mdx

This is related to the issue in DEVDOCS-4442. I came across it and thought I would fix it.
ping {names}
[DEVDOCS-4442]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4442?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-4442: [revise] change blacklist to blocklist

---

docs/api-docs/store-management/shipping/shipping-provider-api.mdx

* Add paragraph about how Shipping Provider APIs should handle incomplete postal codes (from digital wallets)
@bigcommerce/team-shipping 
[DEVDOCS-5284]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5284?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5284 [new]: Shipping Provider API, add digital wallets

---

docs/api-docs/store-management/shipping/shipping-provider-api.mdx

This PR incorporates the feedback made by @vborinsk in [PR 2073](https://github.com/bigcommerce/dev-docs/pull/2073).
- Make a heading for postcodes 
- Clarify that shipping providers can see complete postcodes after order placement 
[DEVDOCS-5284]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5284?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5284 [new]: Shipping Provider API, clarify truncated postcodes 

---

docs/api-docs/webhooks/about-webhooks.mdx

Added the webhook cleanup policy
ping {names}
[DEVDOCS-5493]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5493?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5493: [update] add webhook cleanup policy

---

docs/api-docs/building-checkouts/checkout-consignment.mdx

Changed shipping_address to address because shipping_address is deprecated. See Slack conversation: https://bigcommerce.slack.com/archives/C05BT3PBLAC/p1697742655830829
ping {names}
[DEVDOCS-4888]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4888?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-4888:[Update] change shipping_address to address

---

docs/api-docs/storefront/graphql/graphql-api-examples.mdx
docs/api-docs/storefront/graphql/graphql-api-overview.mdx

removed the feature-complete callout
ping {names}
[DEVDOCS-5571]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5571?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5571: [update] remove feature-complete callout

---

docs/legacy/storefronts/nextjs-commerce-guide.mdx

* Removed Vercel integration details in getting started section, as it's not accurate anymore, post-v2 launch
ping @slsriehl 
[DEVDOCS-5570]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5570?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5570: [revise] Next Commerce v1, remove outdated deployment info

---

docs/stencil-docs/installing-stencil-cli/installing-stencil.mdx
docs/stencil-docs/installing-stencil-cli/stencil-cli-options-and-commands.mdx
docs/stencil-docs/installing-stencil-cli/troubleshooting-your-setup.mdx

Changed the node-sass date to Jan 31, 2024
ping {names}
[DEVDOCS-5578]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5578?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5578: [update] update node-sass date

---

docs/api-docs/catalog/products-overview.mdx

Added note 
ping {names}
[DEVDOCS-5183]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5183?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5183: [update] add note about editing variants in control panel

---

docs/api-docs/getting-started/deprecations-and-sunsets.mdx

* deprecate legacy email templates
[DEVDOCS-5442]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5442?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5442: [deprecate] pre-Handlebars Legacy Email Templates

---

docs/api-docs/catalog/products-overview.mdx

The SME saw the changes and realized that it should be "variant options", not "variants". 
ping {names}
[DEVDOCS-5183]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5183?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

another update for DEVDOCS-5183

---

docs/stencil-docs/installing-stencil-cli/node-sass.mdx

* Revise prose and code blocks
[DEVDOCS-4761]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4761?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-4761: [update] scss compiler upgrade support, revise

---

docs/api-docs/getting-started/about-our-api.mdx

- Removed duplicate heading (Line 201 duplicates Line 147)
- Move "Response Structure" section to go under "Responses"
[DEVDOCS-5561]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5561?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5561 [revise]: About Our APIs, headings

---

docs/api-docs/headless/carts.mdx
docs/api-docs/headless/checkout.mdx
docs/api-docs/headless/end-to-end-guide/rest.mdx
docs/api-docs/headless/guide.mdx
docs/api-docs/headless/orders.mdx
docs/api-docs/headless/tutorial.mdx

* 
* #2071 
* #2083 
ping {names}
[DEVDOCS-5506]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5506?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5506: [update] End-to-End Guide, Headless with REST

---

docs/stencil-docs/page-builder/configuration.mdx

added limit to the documentation
ping {names}
[DEVDOCS-5596]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5596?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5596: [Update] theme variation limit

---

docs/api-docs/webhooks/about-webhooks.mdx

Added webhook requirements to the overview doc.
ping {names}
[DEVDOCS-5645]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5645?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5645: [update] add webhook requirements

---

docs/bigcommerce-for-wordpress/getting-started/install.mdx
docs/bigcommerce-for-wordpress/setup/multi-site.mdx

* Currently verifying, but it seems as though BC4WP still supports MSF
* This reverts commit b990c670da789beadf0e702ddd239ee05b04f193
* #2117
* [SELFDEV-468]
* [DEVDOCS-5647]
ping @bc-tgomez @bc-traciporter @christensenep
[SELFDEV-468]: https://bigcommercecloud.atlassian.net/browse/SELFDEV-468?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEVDOCS-5647]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5647?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

(revert) DEVDOCS-5647: [deprecate] BigCommerce for WordPress, Remove MSF references in BigCommerce for WP

---

README.md

final, update readme
