bigcommerce/dev-docs

markdown/api-docs/getting-started/making-requests.md

The image I added was a broken link. Had to push to the repo to to get the live link for github.

fixed broken image link

---

markdown/stencil-docs/reference-docs/global-objects-and-properties.md

Add locale property to request object

document request.locale

---

markdown/bigcommerce-for-wordpress/getting-started/gutenberg-support.md

Added new page on gutenberg support: gutenberg-support.md

Add Gutenberg Support Article

---

markdown/stencil-docs/reference-docs/other-objects-and-properties-overview.md

Changed the forms.account to forms.edit_account

change forms.account to forms.edit_account

---

markdown/stencil-docs/developing-further/google-analytics-enhanced-ecommerce.md

added custom dimensions and metrics sections

add custom dimensions and metrics section

---

markdown/stencil-docs/reference-docs/other-objects-and-properties-overview.md

Added order confirmation section and checkout object

Add order confirmation section and checkout object

---

spec/json/BigCommerce_Orders_API.oas2.json
spec/yaml/BigCommerce_Orders_API.oas2.yml

Added GET operation to orders/shipment/{id} endpoint

Add GET order/shipment/{id}

---

markdown/stencil-docs/reference-docs/handlebars-helpers-reference.md

Add examples to moment and and helpers and also added hrs between h2s

add examples to helpers and add hrs

---

markdown/stencil-docs/reference-docs/global-objects-and-properties.md

Added is_active property and description to Categories global object.

Devdocs 562 document is active property

---

markdown/stencil-docs/developing-further/theme-updates-and-version-control.md

- shorted article to only review best practices instead of a specific workflow
- added resources

updated original article Theme updates and version control

---

markdown/stencil-docs/reference-docs/common-objects.md
markdown/stencil-docs/reference-docs/global-objects-and-properties.md
markdown/stencil-docs/reference-docs/other-objects-and-properties-overview.md

This PR fixes all the broken links on the Stencil Object Model Reference.

Devdocs 1062 fix broken otp links on reference docs

---

spec/json/BigCommerce_Price_Lists_API.oas2.json

Added variant_id:in to Delete a Price List Record / deletePriceListRecordsByFilter
Changed variant_id to variant_id:in Get All Price List Records getPriceListRecordCollection

DEVDOCS-1037 Fixed variant_id filter

---

markdown/stencil-docs/reference-docs/handlebars-helpers-reference.md

Fixed 2 broken handlebar helpers anchors

Fix handlebars helpers anchors

---

spec/json/BigCommerce_Catalog_API.oas2.json

Changed batch limit from 50 to 10. Re do of an old ticket.

DEVDOCS-1007 Fix Catalog Batch

---

markdown/api-docs/cart-and-checkout/add-to-cart-url.md

Added Parameters section
Restructured article and compressed examples into a single table
Added section on adding multiple products

Add Params, Tables, Multi Product Section

---

beta-documentation/returns-api-PROJECT-2776/returns.json

* Add remaining resources to returns swagger

Add remaining resources to returns swagger

---

beta-documentation/returns-api-PROJECT-2776/returns.json

* Add missing type for return summary
* Improve consistency of wording in descriptions
* Update entity and resource names

Update entity and resource names based on agreed language

---

beta-documentation/returns-api-PROJECT-2776/returns.json

* Add operationIds for each returns operation
* Rename some definitions
* Expand abbreviations
* Add price fields

Add operationIds for each operation; add prices

---

markdown/stencil-docs/reference-docs/handlebars-helpers-reference.md

Added clarifications and corrections related to the `{{getImageSrcset}}` helper.

Corrections and clarifications on the getImageSrcset helper

---

markdown/stencil-docs/reference-docs/handlebars-helpers-reference.md

Further clarification around stencilImage

---

markdown/stencil-docs/reference-docs/handlebars-helpers-reference.md

FIxing formatting on these headers.

Fixing formatting

---

markdown/stencil-docs/reference-docs/handlebars-helpers-reference.md

Clarifications on getImageSrcset

---

beta-documentation/returns-api-PROJECT-2776/returns.json

* Add reason to return item
* Add descriptions to return views

DEVDOCS-1114 Add reason to return item

---

spec/json/BigCommerce_Server_to_Server_Cart_API.oas2.json

Updated Server to Server cart API schema to add additional information for line_items on requested objects

Added call out that line item is option on requested schema objects

---

markdown/stencil-docs/developing-further/catalog-price-object.md

Fixed image link

---

beta-documentation/returns-api-PROJECT-2776/returns.json

Fix descriptions that were copied from another object

Fix copied review descriptions

---

beta-documentation/returns-api-PROJECT-2776/returns.json

Fix double nesting of get response.

Remove double nesting of get returns response

---

markdown/api-docs/developers-guide-headless.md
markdown/api-docs/partner/app-store-approval-requirements.md
markdown/api-docs/store-management/shipping/shipping-overview.md
markdown/bigcommerce-for-wordpress/extending-the-plugin/new-subpage.md
markdown/bigcommerce-for-wordpress/extending-the-plugin/proxy-rest-api-endpoints.md
markdown/legacy/v2-catalog-products/v2-products.md
markdown/legacy/v2-products/v2-v3.md
markdown/stencil-docs/deploying-a-theme/bundling-and-pushing.md
markdown/stencil-docs/developing-further/add-recaptcha-v2.md
markdown/stencil-docs/getting-started/transitioning-to-stencil.md
markdown/stencil-docs/reference-docs/other-objects-and-properties-overview.md
spec/json/BigCommerce_Customers_V3_API.oas2.json

Steven ran the tool again and there was about 20 lingering broken links. Fixed those

Resolve broken links part two

---

markdown/api-docs/getting-started/webhooks/about-webhooks.md

Added a few edits from Dmytro Kuzkin

Devdocs 1132

---

markdown/stencil-docs/reference-docs/other-objects-and-properties-overview.md

- added category to table. Checked using `debug=context`

DEVDOCS-1113 Add category to Product Object

---

spec/json/BigCommerce_Server_to_Server_Cart_API.oas2.json

- Applied Coupon on S2S Cart was showing the coupon object as a nested array. 
Changed Applied Coupon to an object. 
S2S Checkout already correct. 
Without a coupon returns as array with Checkout: https://api.bigcommerce.com/stores/{store_hash}/v3/checkouts/42e15aab-98ef-4717-a1b4-b166108948a2
```
{
"data": {
"id": "42e15aab-98ef-4717-a1b4-b166108948a2",
"cart": {
"id": "42e15aab-98ef-4717-a1b4-b166108948a2",
"customer_id": 0,
"channel_id": 1,
"email": "",
"currency": {
"code": "USD"
},
"base_amount": 159.75,
"discount_amount": 0,
"cart_amount_inc_tax": 172.93,
"cart_amount_ex_tax": 159.75,
"coupons": [],
"discounts": [
{
"id": "b443b131-dde2-43be-b0d9-e6dc4f85b54a",
"discounted_amount": 0
}
],
"line_items": {
"physical_items": [
{
"id": "b443b131-dde2-43be-b0d9-e6dc4f85b54a", …
```

DEVDOCS-1112 Fixed Applied Coupon showing as nested coupon

---

markdown/bigcommerce-for-wordpress/getting-started/app-compatibility.md

DEVDOCS-1111 Fix formatting

---

spec/json/BigCommerce_Orders_API.oas2.json

DEVDOCS-1065 added error format to V2 Orders

---

spec/json/BigCommerce_Catalog_API.oas2.json
spec/json/BigCommerce_Orders_API.oas2.json

- Added include fields to PUT and POST products

DEVDOCS-1104 Add include_fields

---

spec/json/BigCommerce_Customers_V3_API.oas2.json

- added description to PUT customer attributes
- remove type from customer attribute put model
- added description to customer attribute put model

DEVDOCS-1105 Update Customer Attribute PUT

---

markdown/api-docs/developers-guide-headless.md

- Broke up ways to use headless in own sections
- Moved dev workflows to own section
- added a section for apps. Need info from Elizabeth Azide

[WIP] DEVDOCS-1028 Update Headless article

---

markdown/stencil-docs/reference-docs/other-objects-and-properties-overview.md

Added all properties for form.login object and re-formatted table for clarity

Added all objects available for form login and reformatted

---

markdown/stencil-docs/reference-docs/other-objects-and-properties-overview.md

Corrected Cart Items object to reflect accurate keys and properties.

Devdocs 1126 correct cart items

---

spec/json/BigCommerce_Orders_API.oas2.json

Added customer id query parameter to get all orders

Add customer id query param with keys and values

---

markdown/stencil-docs/reference-docs/other-objects-and-properties-overview.md
spec/json/BigCommerce_Orders_API.oas2.json

Update Master from Develop

---

pull_request_template.md
spec/json/BigCommerce_Storefront_Token_API.oas3.json

* Added Stronfront Token API Spec File
* Updated pull request template to include part of the jira url for ease of use

Devdocs 1165 new graphql token endpoint

---

markdown/api-docs/orders/orders-api-overview.md
spec/json/BigCommerce_Orders_API.oas2.json

Add into to orders api docs and add description to value

Devdocs 1115 add info to orders api overview

---

.github/workflows/stoplight_publish.yml

Add stoplight_build.yml that triggers stoplight build when: 
* push events are made to markdown directory of master branch

Add Stoplight Build GitHub Action Workflow

---

markdown/api-docs/getting-started/webhooks/about-webhooks.md

* Re-generated anchor links and ToC to consistent with template
* Clarified blacklisting and minimum threshold in a few spots

DEVDOCS-1184 - Fix Webhook Info

---

markdown/api-docs/cart-and-checkout/cart-and-checkout-overview.md
markdown/api-docs/cart-and-checkout/embedded-checkout.md

A tutorial for creating a standalone Embedded Checkout example with React deployed to Heroku

Devdocs 861 Embedded Checkout

---

markdown/api-docs/cart-and-checkout/channels-sites-routes.html
markdown/api-docs/cart-and-checkout/channels-sites-routes.md

First attempt to create a Channels, Sites and Routes overview

Devdocs 1190

---

docs/legacy/v2-products/v2-v3.md
docs/stencil-docs/reference-docs/handlebars-helpers-reference.md

Fixed typos mentioned in ticket

DEVDOCS-1174 fix typos

---

docs/stencil-docs/reference-docs/handlebars-helpers-reference.md

Fix typos and duplicate issues

DEVDOCS-1176 fixed duplicate and typos

---

docs/api-docs/cart-and-checkout/embedded-checkout-overview.md
docs/api-docs/cart-and-checkout/embedded-checkout-tutorial.md

Made edits based on Ashley's feedback and fixed typos. Also added spec file download in stoplight

DEVDOCS-1206: Polish Embedded Checkout Content

---

__template.md
docs/api-docs/cart-and-checkout/embedded-checkout-overview.md
docs/api-docs/cart-and-checkout/embedded-checkout-tutorial.md

Embedded edits

---

docs/api-docs/cart-and-checkout/embedded-checkout-tutorial.md

Final edits to anchors

---

docs/api-docs/storefront/widgets/widgets-overview.md
docs/api-docs/storefront/widgets/widgets-tutorial.md

* Replaced screenshot with code block
* Fixed some typos

DEVDOCS-1193: Fix Widget Overview and Tutorial Typos

---

__template.md
docs/api-docs/cart-and-checkout/embedded-checkout-overview.md
docs/api-docs/cart-and-checkout/embedded-checkout-tutorial.md
docs/api-docs/payments/payments-api-overview.md
docs/legacy/v2-products/v2-v3.md
docs/stencil-docs/reference-docs/handlebars-helpers-reference.md
docs/stencil-docs/storefront-customization/custom-sass-functions.md

Tested steps for adding custom saas file to Stencil. It was incorrect — added correct steps and cleaned up for clarity

DEVDOCS-943 clarified and corrected custom saas explanation

---

docs/api-docs/storefront/store-front-graphql-api/graphql-storefront-api-overview.md

DEVDOCS-900: Draft GraphQL Docs
* Added Resource section
* Removed stub sections

DEVDOCS-900: Draft GraphQL Docs

---

docs/api-docs/storefront/graphql/graphql-api-overview.md
reference/json/BigCommerce_Storefront_Token_API.oas3.json

DEVDOCS-890: Polish Storefront GraphQL Overview

---

docs/stencil-docs/installing-stencil-cli/installing-stencil.md

* Updated required node version from 8.16 to 10.16

Update Required Node Version

---

docs/legacy/v2-products/v2-v3.md

Fix anchor tag

---

docs/api-docs/developers-guide-headless.md
docs/api-docs/getting-started/building-apps-bigcommerce/building-apps.md
docs/api-docs/store-management/shipping/shipping-provider-api.md
docs/bigcommerce-for-wordpress/extending-the-plugin/amp-for-the-plugin.md
docs/legacy/v2-products/v2-v3.md
docs/stencil-docs/getting-started/transitioning-to-stencil.md

* Fixes all 404s from DEVDOCS-1280 through DEVDOCS-1288

DEVDOCS-1280-88 fixes 404s

---

docs/api-docs/storefront/graphql/graphql-api-overview.md

* Since we're in open beta now and will not be making breaking changes, changed the note about breaking changes to be additive instead

Fix Breaking Changes Callout

---

reference/json/BigCommerce_Catalog_API.oas2.json

* Added image size limit to createCategoryImage

Add image size limit to createCategoryImage

---

docs/api-docs/payments/payments-api-overview.md

Fix indentation

---

docs/bigcommerce-for-wordpress/extending-the-plugin/customization-guide.md

* Fixed table of contents for Wordpress Customization Guide

DEVDOCS-1315 Fixes table of contents

---

.vscode/settings.json
docs/bigcommerce-for-wordpress/extending-the-plugin/customization-guide.html
docs/bigcommerce-for-wordpress/extending-the-plugin/customization-guide.md

Fixes table of contents for wordpress customization guide

DEVDOCS-1315 fixes anchors to downcase

---

reference/json/BigCommerce_Catalog_API.oas2.json

* Changed the name of the video id path param
* Changed datatype to int from string

Update Product Video ID Path Param and Rename

---

docs/stencil-docs/installing-stencil-cli/troubleshooting-your-setup.md

* Just added some formatting to the list maxes

Format the Last PR a bit

---

docs/stencil-docs/installing-stencil-cli/installing-stencil.md

* Verified that instructions work on a fresh install of ubuntu 18.04
* Updated the callout about the tested on version
* Added source ~../bashrc to linux commands incase nvm doesn't work

Update to Ubuntu 18.04

---

reference/json/BigCommerce_Catalog_API.oas2.json

* change the reference for the videoidparam

Fix Product Video ID Parameter Def

---

reference/json/BigCommerce_Catalog_API.oas2.json

* Added Products Scope to Catalog API Ref

Add Product Scope to Catalog API Ref

---

docs/api-docs/getting-started/authentication.md

* Added missing GUI scopes and descriptions

Update Scopes and descriptions

---

reference/json/BigCommerce_Catalog_API.oas2.json

* Added 255 character limit to product image endpoint descriptions

Add Char Limit to Product Image EndpointS

---

docs/api-docs/catalog/products-overview.md

* Copied Postman From the intro into the Complex rules section

Add Run in Postman Button to Complex Rules

---

docs/stencil-docs/javascript-and-event-hooks/npm-tutorials.md

Added cd into theme dir step to install dependency instructions

Add cd theme dir steps

---

docs/api-docs/storefront/graphql/graphql-api-overview.md

* Added section on Complexity Limits

Devdocs 1232 fix info on complexity

---

docs/legacy/blueprint-themes/blueprint-email-templates.md

* Added header row
* Added descriptions for variables

Add descriptions to variables

---

docs/legacy/blueprint-themes/blueprint-email-templates.md

Correct Gift Certificate template variable table

---

reference/json/BigCommerce_Storefront_Token_API.oas3.json

* Fixed an Issue with Store Hash Path Variable

Fix Storefront Token API Base URL

---

reference/json/BigCommerce_Orders_API.oas2.json

* Removed items array from /orders/{order_id}/shipments/{shipment_id} PUT schema
* Removed items array from example request body for /orders/{order_id}/shipments/{shipment_id}

Devdocs 1322 shipment

---

reference/json/BigCommerce_Storefront_Checkout_API.oas2.json

Added store-credit endpoint to storefront checkouts API, and new params to all response bodies

Devdocs 1310 storecred

---

docs/stencil-docs/customizing-checkout/optimized-one-page-checkout.md

Removed extra "s" from path name.

Corrected path name

---

docs/bigcommerce-for-wordpress/extending-the-plugin/proxy-rest-api-endpoints.md

Fix Table Markdown

---

docs/stencil-docs/installing-stencil-cli/stencil-cli-options-and-commands.md

Fix BigCommerce Typoe

---

docs/api-docs/catalog/products-overview.md

Fixed Faceted Search Typo

---

reference/json/BigCommerce_Orders_API.oas2.json

Removes variant ID from Orders API POST schema

Changes Order Post schema to remove Variant ID

---

docs/api-docs/getting-started/about-our-api.html
docs/api-docs/getting-started/about-our-api.md

* Adds sections that explain purpose of each API
* Retitles sections
* Moves server to server information to its own section
* Removes spec download

adds changes

---

docs/stencil-docs/getting-started/transitioning-to-stencil.md

Made OTP links lowercase and removed punctuation

Fix OTP anchors

---

docs/api-docs/getting-started/available-apis.md

* Added Draft of Available APIs Markdown file that will be used as the front page of the API Reference.

Add Available APIs Markdown

---

docs/stencil-docs/getting-started/transitioning-to-stencil.md

Links did not have associated URLs

Add internal links under Technical Differences

---

docs/stencil-docs/installing-stencil-cli/stencil-cli-options-and-commands.md

* Added `--delete` switch to `stencil start` commands table.

DEVDOCS-1493: Add Delete Switch to Stencil Command DocS

---

docs/api-docs/catalog/products-overview.md

DEVDOCS-1363: Change PUT to POST in Create Product Image Example

---

docs/api-docs/store-management/shipping/shipping-provider-api.md

* Added a section to Shipping Providers overview about including product and variant metafields in rate requests.
* Touched up wording a verbiage in a few spots.

DEVDOCS-1346:  Add Product Metafield Details

---

docs/api-docs/partner/app-store-approval-requirements.md

* Clarified the branding requirement a bit
* Also trimmed the content under general requirements a bit

DEVDOCS-1382: Clarify Branding Requirements

---

docs/api-docs/getting-started/webhooks/about-webhooks.md

* Fixed some of the response and request examples in webhooks overview
* Touched the article a bit to make it more concise while I was in there.

DEVDOCS-1388: Fix Webhook Examples

---

reference/BigCommerce_Order_Transactions_API.oas2.yml

* Spelling in `BigCommerce_Order_Transactions_API.oas2.yml`

fix transaction spelling

---

.spelling
docs/api-docs/getting-started/webhooks/webhook-events.md

* Added order Updated event to the list of events corresponding to the order status update payload.

Add Order Updated to Status Change Payload

---

docs/api-docs/payments/payments-api-overview.md

Add Adyen to Supported Cards

---

docs/stencil-docs/installing-stencil-cli/stencil-cli-options-and-commands.md
docs/stencil-docs/storefront-customization/using-disqus.md

Devdocs 1524 add pull command

---

docs/stencil-docs/developing-further/customizing-emails.md
docs/stencil-docs/developing-further/customizing-invoices.md

* Adds article about editing store email templates via WebDav

Adds article on editing email templates via WebDav

---

docs/api-docs/orders/orders-api-overview.md
docs/api-docs/orders/orders-overview.md

Add Use Case to Orders API

---

.textlintrc
docs/api-docs/catalog/products-overview.md

* Replaced postman buttons with request runner buttons
* Edited some of the request and response examples for tidiness and completeness

DEVDOCS-1500: Remove Postman Buttons

---

docs/api-docs/customers/current-customer-api.md

* Added a callout that clarifies the requirement for an App Client ID and secret

Clarify Current Customer Authentication

---

docs/api-docs/catalog/currencies/how-currencies-work.md
docs/api-docs/getting-started/filtering.md
docs/api-docs/getting-started/webhooks/webhook-events.md
docs/api-docs/orders/order-refunds.md
docs/api-docs/orders/orders-api-overview.md
docs/api-docs/store-management/shipping/shipper-hq.md
docs/api-docs/store-management/shipping/shipping-provider-api.md
docs/api-docs/storefront/graphql/graphql-api-overview.md

* minor edits to Dev Center API Docs

Dev Center Minor Edits

---

assets/js/playground_tabs.js

* added two curly braces at the end of Single Product code sample

Fix Single Product GraphQL Error

---

docs/stencil-docs/installing-stencil-cli/stencil-cli-options-and-commands.md

* Made "Deprecated as of v1.23.1" text bold.
* Fix table formatting.

Fix Formatting

---

docs/api-docs/cart-and-checkout/working-sf-apis.md

* Updated code samples
* Re-wrote the tutorial to make it more user-friendly

IN PROGRESS: Re-Write Working with Storefront APIs

---

docs/api-docs/payments/payments-api-overview.md

* Added "50 payment requests per 4 seconds" rate limit to Technical Details > Rate Limits

Add Payments API Rate Limit

---

docs/api-docs/orders/orders-overview.md

* fixed "Server to Server Checkout" broken links

Fix Broken Links

---

docs/api-docs/orders/orders-overview.md

Fix Broken Link

---

reference/BigCommerce_Store_Information_API.oas2.yml

* Added `control_panel_base_url` to /v2/store, which is already in prod.

Add control_panel_base_url to v2/store

---

docs/api-docs/cart-and-checkout/cart-and-checkout-overview.md

* Formatting of code samples
ping @bigcommerce/checkout @vborinsk

CHECKOUT-4792 Format cart and checkout codesamples

---

docs/api-docs/payments/payments-api-overview.md

* updated Payments API sequence diagram

Update Sequence Diagram

---

docs/api-docs/payments/payments-api-overview.md

Update Diagram Link

---

docs/api-docs/partner/becoming-a-partner.md

* Updates Becoming a Partner article to include updated information about creating a Sandbox store

updates becoming a partner

---

docs/api-docs/channels/channels-for-pos.md
docs/api-docs/channels/channels-overview.md

Adding stub files for Channels documentation drafts so I can create the pages in stoplight staging environment and reference the files

Add Stub Files for Channels Drafts

---

docs/api-docs/getting-started/available-apis.md

* Added V2 Redirects to deprecated table.

Add V2 Redirects to Deprecated Table

---

docs/api-docs/getting-started/webhooks/webhook-events.md

* removed extra space to fix table formatting

Remove Extra Space

---

docs/api-docs/getting-started/api-status-codes.html
docs/api-docs/getting-started/api-status-codes.md

* Clarified status codes to include more information for 503. We will now send a store suspended message for stores with administrative/billing issues

DEVDOCS-1812 clarifying status code 503 to include suspension

---

docs/api-docs/getting-started/available-apis.md

* Corrected "Customer Addresses" Resource Description and Endpoint

Fix Resource Description

---

docs/api-docs/orders/orders-api-overview.md

* Removed shipping_provider from Required Fields

Update Shipping an Order

---

docs/api-docs/getting-started/rest-api-authentication.md

Fix "Rate Limts" to "Rate Limits"

Typo fix at rest-api-authentication.md

---

docs/stencil-docs/developing-further/customizing-printable-packing-slips.md

* Clarifies instructions for customizing printable packing sleep

Updates packing slip customization

---

docs/api-docs/customers/customer-login-api.md

Customer Login API changes

---

docs/api-docs/getting-started/best-practices.md

* Added best practices for using SF Cart API. Will link this article in SF Cart spec file once merged

Updates best practices for info on sf cart api

---

docs/api-docs/payments/payments-api-overview.md

Reverts bigcommerce/dev-docs#401

Revert "DEVDOCS-1830 Adds Stripe V3. (Merge Jun 1)"

---

assets/js/playground_tabs.js

* Shortened tab names so tabs will not be under fixed changelog and docs links.

Shorten GraphQL Tab Names

---

docs/api-docs/customers/passwordless-login.md

* Adds an article explaining how to use Passwordless Login

Adds instructions for passwordless customer login to documentation

---

docs/api-docs/getting-started/api-status-codes.md

* Added period to the end of 304 status code description

Minor edit

---

docs/api-docs/getting-started/building-apps-bigcommerce/building-apps.md

Added a space between two words.
Changed "GETrequest" to "GET request" under the Remove User Request(Optional) section

added a space between words

---

docs/api-docs/store-management/shipping/shipping-provider-api.md

Changed "whishing" to "wishing" in the first sentence under Shipping Providers
fixed typo

Fixed typo

---

docs/api-docs/developers-guide-headless.md

Updated the Postman url from www.getpostman.com to www.postman.com 🎸 🚀

Updated Postman URL

---

docs/api-docs/storefront/scripts-overview.md

* Adds changes to Scripts API scopes that now include Login, My Account, Payment Methods pages

Adds changes to scripts API scopes - DO NOT MERGE UNTIL JUNE 30

---

docs/api-docs/channels/building-channel-apps.md
docs/api-docs/channels/channel-app-best-practices.md
docs/api-docs/channels/channel-app-requirements.md
docs/api-docs/channels/channels-extending-existing.md

Polish Channels Docs

---

docs/api-docs/payments/payments-api-overview.md

* Added StripeV3 to accepted gateways for vaulted and non-vaulted CCs.

Add Stripe V3 to Accepted Gateways

---

docs/api-docs/payments/payments-api-overview.md

Add error code that can be returned by Payments API.
ping @bc-marquis-ong

PAYMENTS-5643 Add new error code for Payments API

---

docs/api-docs/channels/channels-extending-existing.md

* Shortened some of the h2 titles to make otp look better

Polish Extending Existing Apps

---

docs/stencil-docs/installing-stencil-cli/live-previewing-a-theme.md

Removed blank space

---

docs/stencil-docs/localization/localizing-stores.md

Added a period to the end of this sentence
Checkout localization is only available for Optimized One-Page Checkout.
added a period

added a period at the end of a sentence

---

docs/stencil-docs/javascript-and-event-hooks/npm-tutorials.md

changed section~.~: to sections:
made small editorial change

editorial change

---

docs/stencil-docs/customizing-checkout/checkout-confirmation-injection.md

changed "page by by using the script" to "page by using"
removed duplicate words

removed duplicate words

---

docs/stencil-docs/developing-further/google-analytics-enhanced-ecommerce.md

* Fix some quotation marks and remove partial sentence

Google Analytics Enhanced Ecommerce: Fix some quotation marks and remove partial sentence

---

docs/stencil-docs/customizing-checkout/checkout-sdk-quickstart.md

Made this one small change in the introductory information
To illustrate that point, this tutorial will walk through
to 
to illustrate this point, this tutorial will walk through

changed "that" to "this"

---

docs/stencil-docs/storefront-customization/theme-assets.md

Moved text a little in an attempt to align the tables in the Variables and Mixin section.
aligned tables

align tables in file

---

docs/stencil-docs/javascript-and-event-hooks/adding-javascript.md

Added a period to the following sentence: "Notice the page types correspond to the html pages in cornerstone/templates/pages/"

Added a period at the end of the sentence

---

docs/api-docs/apps/apps-quick-start.md

* Added App Quick Start Tutorial Draft

Building Apps Quick Start Tutorial

---

specs/BigCommerce_Order_Transactions_API.oas2.yml

* Rename payment-method-id to payment_method_id so it reflects what the API returns.

DEVDOCS-1992 Rename payment method id

---

docs/api-docs/storefront/scripts-overview.md

Made changes per review and also fixed capitalization

Additional edits to scripts.md 

---

docs/api-docs/cart-and-checkout/working-sf-apis.md

Fixed section headings
Removed passive voice
Removed extra words in order to be more concise
See above.

Updated Working-sf-apis.md per style guide

---

docs/api-docs/apps/guide/apps-05-oauth.md

* Finished Building Apps 05: Implementing OAuth Flow

DEVDOCS-1979: Apps - Prod | Building Apps 05: Implementing OAuth Flow

---

docs/api-docs/orders/orders-overview.md

Updated section headings
Removed passive voice to improve readability
fixed a typo
Made updates for IA refactor epic.

Updated orders-overview per style guide

---

docs/api-docs/apps/guide/apps-06-callbacks.md

DEVDOCS-1980: Apps - Prod | Building Apps 06: Handling Callbacks

---

docs/api-docs/apps/guide/apps-07-users.md

DEVDOCS-1981: Apps - Prod | Building Apps 07: Supporting Multiple Users

---

docs/api-docs/cart-and-checkout/embedded-checkout-tutorial.md

Made a few updates per the devdocs style guide

Updated Embedded Checkout Tutorial for IA Refactor

---

docs/api-docs/storefront/scripts-overview.md

Fixed links under On this Page
fixed navigation links under "On this page"

Fixed broken html links in scripts-overview.md

---

specs/BigCommerce_Order_Transactions_API.oas2.yml

* Add payment_method_id to order transaction example response

DEVDOCS-1992 Add payment_method_id to order transaction example response

---

docs/api-docs/getting-started/webhooks/about-webhooks.md
docs/stencil-docs/storefront-customization/theme-assets.md
specs/BigCommerce_Order_Transactions_API.oas2.yml

* Webhooks overview IA refactor changes

Devdocs 2016 hooks overview

---

docs/api-docs/apps/guide/apps-11-best-practices.md

* adding content to best practices

DEVDOCS-1998: Apps - Prod | Building Apps 11: Best Practices

---

docs/api-docs/apps/guide/apps-12-requirements.md

* added approval requirements.

DEVDOCS-1999: Apps - Prod | Building Apps 12: Approval Requirements

---

docs/api-docs/getting-started/authentication.md

Removed passive voice
changed curly apostrophes to straight
Ensured section headings were written correctly
see above

Update authentication.md per style guide

---

docs/api-docs/catalog/currencies/currencies-overview.md

In the Preconfiguring the Store, the bullet point "Stripe Payment Gateway" was replaced with "Multi-currency compatible payment gateway" and linked to the Managing Currencies page.

Update currencies-overview.md (DEVDOCS-2095)

---

docs/stencil-docs/developing-further/theme-updates-and-version-control.md

* Applied style guide updates.

DEVDOCS-2091: Theme Updates and Version Control

---

docs/api-docs/apps/guide/apps-09-ui.md
docs/api-docs/apps/guide/apps-10-buttons.md

* Renamed creating install buttons to "Creating External Install Buttons".

DEVDOCS-2104: Rename Creating Install Buttons

---

docs/stencil-docs/deploying-a-theme/naming-your-theme.md

* applied sentence case
* updated code samples
* added code font

DEVDOCS-2086: Dev Center | Theme Docs | Theme Variations

---

docs/stencil-docs/deploying-a-theme/checking-a-themes-size.md

* applied sentence case
* updated links
* changed table formatting to markdown
* added code font

DEVDOCS-2087: Dev Center | Theme Docs | Checking a Theme's Size

---

docs/stencil-docs/javascript-and-event-hooks/customizing-javascript.md

DEVDOCS-2077: Customizing JavaScript

---

docs/api-docs/catalog/products-overview.md

* Fixed product modifier adjuster requests.

fix(DEVDOCS-2132): Missing ID for Updating Modifier Value

---

docs/bigcommerce-for-wordpress/getting-started/supported-features.md

Changed Wordpress to WordPress throughout the article.

Updated supported-features.md

---

docs/api-docs/cart-and-checkout/open-source-checkout.md

* Removed duplicate header.
* Added 2 sentences under the Open Source Checkout header to clarify one needs to build, deploy and configure the checkout to view and test changes.

DEVDOCS-1461: Clarification

---

docs/stencil-docs/configure-store-design-ui/defining-global-styles.md

* updated table of contents
* removed Store Design mention
* updated Models link
* minor formatting changes

DEVDOCS-2178: Update Global Styles

---

docs/api-docs/getting-started/available-apis.md

* /catalog/products/{id}/buld-pricing-rules -> /catalog/products/{id}/bulk-pricing-rules

fix typo: buld-pricing-rules

---

docs/api-docs/cart-and-checkout/open-source-checkout.md
docs/api-docs/catalog/products-overview.md
docs/api-docs/customers/customers-subscribers-overview.md
docs/api-docs/getting-started/available-apis.md
docs/stencil-docs/configure-store-design-ui/defining-global-styles.md
docs/stencil-docs/deploying-a-theme/bundling-and-pushing.md
docs/stencil-docs/reference-docs/handlebars-helpers-reference.md
package-lock.json

Reverts bigcommerce/dev-docs#689

Revert "DEVDOCS-2178: Update Defining Global Styles"

---

docs/api-docs/getting-started/filtering.md

implemented suggestions

---

docs/api-docs/apps/guide/apps-12-requirements.md

Fixed the broken link under Next steps

Updated apps-12-requirements

---

docs/api-docs/getting-started/webhooks/webhook-events.md

* Added variant deleted and modifier deleted to list of fields triggering product update event.

DEVDOCS-2197: Fix Missing Product Updated Tigger

---

docs/api-docs/customers/customers-subscribers-overview.md

Fix quotes in JSON on customers and subscribers overview page

Fix quotes in JSON on customers and subscribers overview page

---

docs/api-docs/getting-started/best-practices.md

* replaced Dev Tools with Developer Portal
* added API Rate Limit table
* added new resources

DEVDOCS-2263: Updated per Style Guide

---

docs/api-docs/storefront/widgets/widgets-overview.md

DEVDOCS-2227: removed global regions

---

docs/api-docs/apps/guide/apps-12-requirements.md

* Polished and updated app store approval requirements.

DEVDOCS-2217: Polish Approval Requirements

---

docs/api-docs/apps/guide/apps-13-publishing.md

DEVDOCS-2218: Polish Publishing Apps

---

docs/api-docs/getting-started/rest-api-authentication.md

Rename dev tools to Developer Portal

DEVDOCS-2287: rename dev tools

---

docs/api-docs/apps/guide/apps-04-devloper-portal.md

Fix Typo in Callout

---

docs/api-docs/storefront/widgets/widgets-overview.md

* removed extra lines
* added html

DEVDOCS-2227: Updated formatting

---

docs/api-docs/getting-started/authentication.md

I found an occurrence of "client_id" in api-docs that needed to be removed.

DEVDOCS-2297: Update authentication.md

---

docs/api-docs/apps/tutorials/apps-id.md

renamed devtools to developer portal

DEVDOCS-2287: Update apps-id.md

---

docs/api-docs/partner/becoming-a-partner.md

Consolidated Partner Program information into Becoming a partner.md

DEVDOCS-2268: Update becoming a partner.md

---

docs/api-docs/partner/marketing-api-overview.md

* Created Marketing API Overview article.

DEVDOCS-2305: Created Marketing API Overview article

---

docs/api-docs/partner/resources.md

* fixed sample apps list
* fixed BigCommerce in OmniAuth BigCommerce strategy

fix partner resources

---

docs/stencil-docs/reference-docs/handlebars-helpers-reference.md

* removed camelCase from anchor tags

DEVDOCS-2274: Removed camelCase from anchor tags

---

docs/api-docs/customers/customers-subscribers-overview.md

* fixed broken links
* fixed the order of resources 
* removed empty lines

DEVDOCS-2317: Fixed broken links

---

docs/api-docs/channels/building-channel-apps.md
docs/api-docs/storefront/widgets/widgets-tutorial.md

* Fixed request runner on widget's tutorial.
* Fixed one in another article while I was doing it.

DEVDOCS-2242: Fix Webhook Request Runner

---

docs/api-docs/customers/customers-subscribers-overview.md

* added OAuth table
* updated OTP
* added Subscribers API definition

DEVDOCS-2339: Added Subscribers API definition

---

docs/api-docs/payments/payments-api-overview.md

Reverts bigcommerce/dev-docs#662

Revert [Merge Oct 30]Updated payments-api-overview"

---

docs/stencil-docs/localization/multi-language-checkout.md

removed div tags in order to fix the text wrapping issue

Update multi-language checkout.md

---

docs/api-docs/developers-guide-headless.md

* Added section on storefront channels with screenshot and link to building storefront channels tutorial.

DEVDOCS-2302: Add Link to  Headles Guide

---

docs/api-docs/channels/channels-storefront-tutorial.md

* Added screenshot that shows protected and custom sections together.

DEVDOCS-2353: Add Custom Settings Screenshot

---

docs/stencil-docs/installing-stencil-cli/installing-stencil.md

DEVDOCS-2368: Update installing-stencil.md

---

docs/stencil-docs/localization/multi-language-checkout.md

Updated link to checkout-en.json

DEVDOCS-2370: Update multi-language-checkout.md

---

assets/json/checkout-en.json
docs/stencil-docs/localization/multi-language-checkout.md

Copied contents of [en.json](https://github.com/bigcommerce/checkout-js/blob/master/src/app/locale/translations/en.json) from the checkout-js repo into this file.

DEVDOCS-2370: Update checkout.en.json

---

docs/stencil-docs/localization/multi-language-checkout.md

The original ticket indicated that only 2 links needed to be changed. However, I found 2 more occurrences of this old link in the file as I reviewed my changes. I should update these as well. Sorry for sending these piecemeal.

DEVDOCS-2370: Update multi-language-checkout.md file

---

assets/js/playground_tabs.js
docs/api-docs/storefront/graphql/graphql-api-examples.md

* Remove mention of deprecated fields from examples
* Minor clarifications
* Update examples to reduce the total number and remove deprecated fields
* Clean up code so you can actually read the queries

Update examples to remove deprecated fields

---

docs/api-docs/storefront/widgets/widgets-tutorial.md

* updated code examples
* updated resources
* updated OTP

DEVDOCS-2354: Updated widgets tutorial

---

docs/stencil-docs/page-builder/widget-ui-schema.md

* removed regex input reference

DEVDOCS-2380: Removed regex reference

---

docs/api-docs/orders/orders-api-overview.md

DEVDOCS-2284: Remove duplicate table

---

docs/api-docs/payments/payments-api-overview.md

Add Bolt to the "support stored card" list
Add Bolt to the "support credit card" list

DEVDOCS-2383:Added Bolt to list of payment gateways

---

docs/api-docs/storefront/widgets/product-widget-tutorial.md

* added a new line to Create a Placement example

DEVDOCS-2437: Added space in code example

---

docs/stencil-docs/page-builder/page-builder-overview.md

* added reference to tutorials
* updated links

DEVDOCS-2445: Updated links, added reference to tutorials

---

docs/stencil-docs/storefront-customization/using-custom-fonts-and-icons.md

* replaced Store Design with Page Builder

DEVDOCS-2455: Removed Store Design reference

---

docs/api-docs/management-apis/contextual-filters.md

* added links to Search Filters endpoints

Updated endpoint links

---

docs/api-docs/management-apis/contextual-filters.md

* added a link to Product Filtering

Devdocs 2391 links

---

docs/api-docs/partner/support.md

Fix minor typos

---

docs/api-docs/storefront/widgets/global-regions-tutorial.md
docs/api-docs/storefront/widgets/product-widget-tutorial.md
docs/api-docs/storefront/widgets/widget-versioning-tutorial.md
docs/api-docs/storefront/widgets/widgets-code-samples.md
docs/api-docs/storefront/widgets/widgets-tutorial.md

DEVDOCS-2483: Updated links to resources

---

docs/api-docs/apps/tutorials/apps-id.md
docs/api-docs/customers/customer-login-api.md
docs/api-docs/payments/payments-api-overview.md
docs/api-docs/storefront/widgets/widgets-overview.md
docs/stencil-docs/configure-store-design-ui/defining-ui-options.md
docs/stencil-docs/localization/translation-keys.md
docs/stencil-docs/reference-docs/other-objects-and-properties-overview.md

Fix quotes

---

docs/api-docs/building storefronts/nextjs-commerce-guide.md

* added table of contents to Next.js Commerce article

Nextjs commerce toc

---

docs/stencil-docs/reference-docs/handlebars-helpers-reference.md

* added a newline after a codeblock
* fixed getObject helper error

Fixed getObject error

---

docs/api-docs/customers/customers-subscribers-overview.md

This PR replaces [PR 980](https://github.com/bigcommerce/dev-docs/pull/980).
* Updated On This Page
* Added transition sentence
* Updated Resources links

DEVDOCS-2554: Updated links, added transition sentence

---

docs/stencil-docs/reference-docs/handlebars-helpers-reference.md

* changed some of the handlebars code notations to html for better readability.

Handlebars Helpers: Updated code notations

---

docs/api-docs/management-apis/email-templates/overview.md

* Added Email Templates Overview

DEVDOCS-2548: Add Email Templates Overview

---

docs/legacy/v2-catalog-products/v2-brands.md
docs/legacy/v2-catalog-products/v2-bulk-pricing.md
docs/legacy/v2-catalog-products/v2-categories.md
docs/legacy/v2-catalog-products/v2-custom-fields.md
docs/legacy/v2-catalog-products/v2-option-values.md
docs/legacy/v2-catalog-products/v2-product-images.md
docs/legacy/v2-catalog-products/v2-product-options.md
docs/legacy/v2-catalog-products/v2-product-reviews.md
docs/legacy/v2-catalog-products/v2-product-rules.md
docs/legacy/v2-catalog-products/v2-product-sku.md
docs/legacy/v2-catalog-products/v2-product-videos.md

DEVDOCS-2573: Updated API links

---

docs/api-docs/getting-started/filtering.md

* updated `attribute:in` expression

DEVDOCS-2580: Updated attribute:in expression

---

docs/api-docs/cart-and-checkout/embedded-checkout-overview.md

* Updated embedded checkout overview to note that page must share same root domain as BC storefront. 
* Fixed a couple of minor capitalization issues

Devdocs 2565 update embedded checkout overview

---

docs/api-docs/payments/payments-api-overview.md

Updated list of providers supported in public api
ping @bigcommerce/dev-docs @bigcommerce/payments

Update list of providers supported in public payment api

---

docs/api-docs/orders/order-refunds.md

* Clarified request parameters with comments
* Added examples for different types of refunds
* Added section to FAQ about order level refunds.

DEVDOCS-2663: Add Order Level Refund Examples

---

docs/api-docs/provider-apis/tax/overview.md

* Added overview for Tax Provider API.

DEVDOCS-2192: Tax Provider API

---

docs/api-docs/provider-apis/tax/overview.md

Added "Sandbox tax provider configuration" section and made other minor improvements.
Previously there was not much content describing sandbox tax provider functionality, leading to confusion and additional back and forth communication with tax providers as they were integrating to Tax Provider API.
Ping: @aglensmith

docs(tax): DEVDOCS-2730 Added sandbox section, other minor improvements

---

docs/api-docs/storefront/widgets/product-widget-tutorial.md

* updated code examples
* added a section on GraphQL queries

DEVDOCS-2728: Updated code examples, added graphql query callout

---

docs/api-docs/partner/create-a-sandbox.md
docs/api-docs/partner/dev-portal-overview.md
docs/api-docs/partner/resources.md
docs/api-docs/partner/support.md

* updated partner support resources

DEVDOCS-2541: Updated support resources

---

docs/api-docs/partner/becoming-a-partner.md

* Added types of programs
* Updated resources
* Added training and support information

Updated program information

---

docs/api-docs/catalog/pricing-order-operation.md

* added Product option set to the list

DEVDOCS-2733: Added product option set

---

docs/api-docs/getting-started/webhooks/webhook-events.md

* Added the `store/channel` webhook events
* Put event sections in alphabetical order
* Changed title from "Webhooks" to "Webhook Events"
* Removed old anchor links

Add Channel Webhook Events

---

docs/api-docs/provider-apis/tax/overview.md

Before, we suggested that multiple sandbox providers within one primary provider is ok.
After, we suggest this is not ok and not the preferred approach with some reasons why.
ping @bigcommerce/shipping @uwikaiddi

Improve Tax Provider API sandbox description

---

docs/api-docs/getting-started/webhooks/setting-up-webhooks.md

Fix Webook Typos

---

docs/bigcommerce-for-wordpress/extending-the-plugin/code-reference.md

* added usage notes section to be expanded upon
* added Classes -> Refinery usage clarification

Devdocs 2655 - add information about $refinery filter

---

docs/bigcommerce-for-wordpress/getting-started/supported-features.md

Devdocs 2751 add promo codes to supported bc4 wp features

---

docs/legacy/blueprint-themes/recaptcha-two.md

* Remove IE11 from supported browsers

Remove IE11 from supported browsers for CP

---

docs/partner-apps/bundleb2b/b2b-edition.md

DEVDOCS-2885 - Update BundleB2B API link

---

docs/api-docs/apps/guide/apps-12-requirements.md
docs/api-docs/catalog/products-overview.md

* updated Functionality approval requirements
* made minor edits

DEVDOCS-2889: Update App Approval Requirements

---

docs/api-docs/apps/guide/apps-12-requirements.md
docs/api-docs/catalog/products-overview.md

* Removed the "beta" label from Product Sort Order API

DEVDOCS-2900: remove beta label

---

docs/api-docs/apps/guide/apps-12-requirements.md
docs/stencil-docs/storefront-customization/localizing-variation-descriptions.md

* added Localizing Variation Descriptions article

Devdocs 2925

---

docs/api-docs/cart-and-checkout/embedded-checkout-tutorial.md

Added edits as specified in the JIRA ticket.

Updated embedded -checkout-tutorial.md

---

docs/api-docs/apps/apps-quick-start.md

* updated the quick start tutorial
* added links to the sample app repo
* updated resources

DEVDOCS-2969: Updated app quick start

---

docs/api-docs/management-apis/email-templates/overview.md
docs/stencil-docs/installing-stencil-cli/live-previewing-a-theme.md

* add message regarding transactional email character limit

Devdocs-2961 update the documentation for transactional emails

---

docs/api-docs/apps/tutorials/sample-app-next/step-1-setup.md

* added On This Page section to Step 1

DEVDOCS-2591: Added OTP to step 1

---

docs/api-docs/channels/channels-extending-existing.md

* add a note regarding depreciation of `google_shopping` and `marketing` pair
* add a note about newly added `google` platform for type `marketing` and `marketplace`

Devdocs 2863

---

docs/api-docs/building-storefronts/nextjs-commerce-guide.md

* minor edits to comply with the style guide

DEVDOCS-3063: Added edits per the style guide

---

docs/api-docs/apps/apps-quick-start.md
docs/api-docs/apps/tutorials/sample-app-next/step-2-connect-to-bc.md
docs/api-docs/apps/tutorials/sample-app-next/step-3-integrate-api.md

* Added Firebase setup instructions
* Added OAuth scope to quick start

DEVDOCS-3079: Re-add Firebase setup instructions

---

docs/api-docs/getting-started/webhooks/webhook-events.md

* Fixes the channel webhooks table
| Before | After |
| - | - |
| <img width="808" alt="Screen Shot 2021-09-08 at 12 16 22" src="https://user-images.githubusercontent.com/10539418/132554754-afb626c2-9ed1-4c42-b6d7-39ffcc2e09ba.png"> | <img width="719" alt="Screen Shot 2021-09-08 at 12 16 46" src="https://user-images.githubusercontent.com/10539418/132554786-d637a5b2-e31d-4d72-8809-6bad59b74277.png"> |

fix: channel-webhooks table

---

docs/api-docs/building-checkouts/checkout-customizability.md

Update image in checkout customizability.md

---

docs/stencil-docs/deploying-a-theme/theme-best-practices.md

jsContext typo mistake

---

docs/stencil-docs/localization/localizing-stores.md

Updated links for the language files.

Update links to language files

---

docs/api-docs/getting-started/api-status-codes.md

* Add `207` status code to `docs/api-docs/getting-started/api-status-codes.md`

DEVDOCS-2589 - Add HTTP 207 Status

---

docs/api-docs/apps/guide/apps-13-publishing.md

* moved tables to correct header

DEVDOCS-3141 switch tables to match headers

---

docs/stencil-docs/installing-stencil-cli/installing-stencil.md

* Master merge (#1075)
* Dev merge (#1074)
* Update handlebars-helpers-reference.md (#731)
Co-authored-by: aglensmith <aglensmith@gmail.com>
Co-authored-by: Uwana Ikaiddi <uwana.ikaiddi@bigcommerce.com>
* Update resources (#732)
Co-authored-by: Uwana Ikaiddi <uwana.ikaiddi@bigcommerce.com>
* DEVDOCS-2133: Update Webhooks Retries Info (#734)
* DEVDOCS-2133: Update Webhooks Retries Info
* Update docs/api-docs/getting-started/webhooks/about-webhooks.md
Co-authored-by: Uwana Ikaiddi <uwana.ikaiddi@bigcommerce.com>
* DEVDOCS-2197: Fix Missing Product Updated Tigger (#735)
Co-authored-by: Uwana Ikaiddi <uwana.ikaiddi@bigcommerce.com>
* DEVDOCS-2228: Add Button Widget Code Sample (#736)
* button widget code sample
* removed extra space
* fixed spacing issue
Co-authored-by: Uwana Ikaiddi …

Dev merge (#1322)

---

docs/api-docs/apps/tutorials/sample-app-next/step-1-setup.md
docs/api-docs/apps/tutorials/sample-app-next/step-2-connect-to-bc.md
docs/api-docs/apps/tutorials/sample-app-next/step-3-integrate-api.md

* revised nextjs tutorial to npm i firebase@^8xx, because v9 breaks our app.

DEVDOCS-3240: Add tested version reference to indicate breaking change at firebase9

---

docs/api-docs/cart-and-checkout/add-to-cart-url.md

* code example revised to use promises, because JavaScript is asynchronous

DEVDOCS-3243: Add a cart URL tutorial only adds last product to the cart

---

docs/api-docs/building-storefronts/abandoned-carts.md
docs/stencil-docs/customizing-checkout/checkout-confirmation-injection.md
docs/stencil-docs/localization/multi-language-checkout.md
docs/stencil-docs/reference-docs/handlebars-helpers-reference.md
docs/stencil-docs/storefront-customization/custom-sass-functions.md
docs/stencil-docs/storefront-customization/page-composition-and-styling.md

Modified docs/api-docs/building-storefronts/abandoned-carts.md

---

docs/api-docs/building-checkouts/checkout-consignment.md

* see list of individual commits in this child PR -- I was descriptive.

DEVDOCS-3024 *revisions to main PR 1331*

---

docs/api-docs/storefront/widgets/widget-builder.md

* moved sections, retitled, added references to directory in which the user-developer works

DEVDOCS-2135 Sarah's proposed changes

---

docs/api-docs/apps/guide/apps-01-introduction.md
docs/api-docs/apps/guide/apps-03-developing.md
docs/api-docs/apps/guide/apps-06-callbacks.md
docs/api-docs/apps/guide/apps-07-users.md
docs/api-docs/apps/guide/apps-08-events.md
docs/api-docs/apps/guide/apps-09-ui.md
docs/api-docs/apps/guide/apps-10-buttons.md

Nelify to Netlify

---

docs/api-docs/getting-started/webhooks/webhook-events.md

no ticket, just fixed the table

Fixed table

---

docs/bigcommerce-for-wordpress/setup/multi-site.md

DEVDOCS-2929
- Added Callout Information about Subdirectories Support
- Added callout snippet around the channel site API not accepting paths on a domain as the site's URL.
- Cleaned up headers and reworked some content for better flow.

Devdocs 2929 modified multi site

---

docs/api-docs/building-checkouts/checkout-consignment.md

[DEVDOCS-3024](https://jira.bigcommerce.com/browse/DEVDOCS-3024)
Fixed links in the article

fixed-links-checkout-consignment.md

---

docs/bigcommerce-for-wordpress/setup/multi-site.md

DEVDOCS-2929 (child branch edit) nested divs

---

docs/bigcommerce-for-wordpress/setup/multi-site.md

* Removed passive voice from line 161
* Adjusted adjective of "left-hand side" Line 33
* Corrected subject verb agreement in line 170

Dev docs 2929 added edits

---

docs/api-docs/payments/payments-api-overview.md

* removed list of payment providers so the info isn't duplicated with support

removed payment list

---

assets/csv/tracking_carrier_values.csv

* Add Mainfreight to CSV file
* Small formatting changes so CSV renders as a table

Devdocs 3314 - Add Mainfreight to the list of Other Tracking Carriers

---

toc.json

remove html-encoded chars from title strings -- "&amp;" to "&"

cosmetic toc.json title changes

---

docs/api-docs/building-checkouts/checkout-customizability.md

Devdocs 3434

---

docs/stencil-docs/customizing-checkout/open-checkout-quick-start.md
docs/stencil-docs/storefront-customization/directory-structure.md

remove on this page

---

docs/api-docs/getting-started/webhooks/about-webhooks.md

Fixed subject-verb agreement for a caption

Fixed subject-verb agreement

---

docs/api-docs/cart-and-checkout/open-source-checkout.md
docs/api-docs/storefront/widgets/widgets-tutorial.md
docs/stencil-docs/installing-stencil-cli/troubleshooting-your-setup.md

Fixed markdown formatting issues for lists

Devdocs 3534 markdown list formatting

---

docs/api-docs/apps/guide/apps-08-events.md
docs/api-docs/apps/tutorials/apps-id.md
docs/api-docs/building-checkouts/checkout-consignment.md
docs/api-docs/building-storefronts/abandoned-carts.md
docs/api-docs/catalog/products-overview.md
docs/api-docs/channels/building-channel-apps.md
docs/api-docs/channels/channels-extending-existing.md
docs/api-docs/channels/channels-pos-tutorial.md
docs/api-docs/channels/channels-quick-start.md
docs/api-docs/channels/channels-storefront-tutorial.md
docs/api-docs/getting-started/making-requests.md
docs/api-docs/getting-started/webhooks/about-webhooks.md
docs/api-docs/getting-started/webhooks/setting-up-webhooks.md
docs/api-docs/headless/carts.md
docs/api-docs/headless/orders.md
docs/api-docs/headless/products.md
docs/api-docs/management-apis/contextual-filters.md
docs/api-docs/management-apis/email-templates/overview.md
docs/api-docs/orders/order-refunds.md
docs/api-docs/orders/orders-api-overview.md
docs/api-docs/partner/marketing-api-overview.md
docs/api-docs/storefront/widgets/product-widget-tutorial.md
docs/api-docs/storefront/widgets/widget-versioning-tutorial.md
docs/api-docs/storefront/widgets/widgets-tutorial.md

-Commented out request runner buttons
-Did not remove/change [request_runner.md](https://github.com/bigcommerce/dev-docs/blob/a948dcd25ca30931a0564d7f80e6f80418d31158/_project/request_runner.md)

Devdocs 3423 request runner

---

docs/stencil-docs/reference-docs/front-matter-reference.md

Front Matter Reference: fixed cases where numbers in comments did not match the code to their left
This PR needs to be merged into the master

Update front-matter-reference.md (#1391)

---

docs/api-docs/getting-started/webhooks/webhook-events.md

* change headers to text to prevent nav display

Devdocs 3571 webhooks headers

---

.stoplight.json

* unexcluded custom order confirmation page

unexclude custom order confirmation

---

docs/api-docs/apps/guide/apps-11-best-practices.md
docs/api-docs/building-checkouts/checkout-consignment.md
docs/api-docs/cart-and-checkout/working-sf-apis.md
docs/api-docs/customers/current-customer-api.md
docs/api-docs/developers-guide-headless.md
docs/api-docs/getting-started/best-practices.md
docs/api-docs/storefront/graphql/graphql-api-examples.md
docs/bigcommerce-for-wordpress/extending-the-plugin/customization-guide.md
docs/bigcommerce-for-wordpress/setup/plugin-settings.md
docs/bigcommerce-for-wordpress/setup/troubleshooting.md
docs/stencil-docs/page-builder/third-party-widgets.md
docs/stencil-docs/reference-docs/global-objects-and-properties.md
docs/stencil-docs/reference-docs/other-objects-and-properties-overview.md
docs/stencil-docs/storefront-customization/using-front-matter.md

##Background:
To fix issues with code blocks, prior PRs/tickets removed HTML Code Tags and replaced them with backticks.
##What this pull request does: 
Fixes markdown issues that still remained (e.g. resulted from using backticks, other issues on the same line)
1. ![Words Don't Show](https://user-images.githubusercontent.com/96258747/156636045-718f5ba2-fe0f-4169-a189-6d46328b5dac.PNG)
2. ![Less Than and Greater Than Signs](https://user-images.githubusercontent.com/96258747/156635484-22cc30cc-cf94-4e3c-ac69-e1ddcbf2cdfa.PNG)

Devdocs 3532 html code tags

---

docs/stencil-docs/page-builder/widget-ui-schema.md

Updated the widgets UI input types link

Update Widget UI Input Types link

---

docs/bigcommerce-for-wordpress/extending-the-plugin/bigcommerce-for-wordpress-cron.md

* Added docs/bigcommerce-for-wordpress/extending-the-plugin/bigcommerce-for-wordpress-cron.md
Co-authored-by: traci707 <64287776+traci707@users.noreply.github.com>
Co-authored-by: bc-andreadao <96258747+bc-andreadao@users.noreply.github.com>
Co-authored-by: Sarah Riehl <sarah.riehl@bigcommerce.com>

Bc4wp cron sync to staging (#1429)

---

docs/msf/managing-store-configuration.md
docs/msf/msf-api-guide.md
docs/msf/msf-app-compatibility.md
docs/msf/msf-overview.md

* verified links
* new redirects
* light copyediting
once more, with feeling.

Make all MSF narrative links human-readable

---

docs/api-docs/apps/guide/apps-01-introduction.md
docs/api-docs/apps/guide/apps-02-types.md
docs/api-docs/apps/guide/apps-03-developing.md
docs/api-docs/apps/guide/apps-05-oauth.md
docs/api-docs/apps/guide/apps-06-callbacks.md
docs/api-docs/apps/guide/apps-07-users.md
docs/api-docs/apps/guide/apps-08-events.md
docs/api-docs/apps/guide/apps-09-ui.md
docs/api-docs/apps/guide/apps-10-buttons.md
docs/api-docs/apps/guide/apps-11-best-practices.md
docs/api-docs/apps/guide/apps-12-requirements.md
docs/api-docs/apps/guide/apps-13-publishing.md
docs/api-docs/channels/channels-toolkit-reference.md
docs/api-docs/partner/dev-portal-overview.md

DEVDOCS-3599 Fixed figma links

---

docs/stencil-docs/configure-store-design-ui/defining-global-styles.md
docs/stencil-docs/getting-started/stencil-technology-stack.md
docs/stencil-docs/getting-started/transitioning-to-stencil.md
docs/stencil-docs/installing-stencil-cli/live-previewing-a-theme.md
docs/stencil-docs/localization/localization-tutorial.md
docs/stencil-docs/localization/translation-keys.md
docs/stencil-docs/storefront-customization/custom-templates.md
docs/stencil-docs/storefront-customization/theme-accessibility.md
docs/stencil-docs/storefront-customization/theme-assets.md
docs/stencil-docs/storefront-customization/using-custom-fonts-and-icons.md

Changed Youtube links so they stop embedding in our docs

DEVDOCS-3533: youtube links

---

docs/api-docs/payments/payments-api-overview.md

added lists of payment gateways

DEVDOCS-3702: Update payments-api-overview

---

docs/api-docs/getting-started/webhooks/webhook-events.md

* Scope creep from PR #1426
* Cleanup webhooks article
* style guide, 
* cleaner form, 
* link channels section to MSF-aware channels webhooks article

style guide, cleaner form, link channels section to MSF-aware channels webhooksarticle

---

docs/legacy/blueprint-themes/blueprint-and-developer-mode.md
docs/legacy/blueprint-themes/blueprint-email-templates.md
docs/legacy/blueprint-themes/lng-variables.md
docs/stencil-docs/deploying-a-theme/troubleshooting-theme-uploads.md

Changed bold syntax from HTML to MD

DEVDOCS-3496: html to md

---

docs/api-docs/payments/payments-api-overview.md
docs/legacy/blueprint-themes/blueprint-and-developer-mode.md
docs/legacy/blueprint-themes/blueprint-email-templates.md
docs/legacy/blueprint-themes/lng-variables.md
docs/stencil-docs/deploying-a-theme/troubleshooting-theme-uploads.md

* [DEVDOCS-3496](https://jira.bigcommerce.com/browse/DEVDOCS-3496) - #1425 - @bc-andreadao 
* [DEVDOCS-3702](https://jira.bigcommerce.com/browse/DEVDOCS-3702)A - #1459 - @traci707 
* [DEVDOCS-3702](https://jira.bigcommerce.com/browse/DEVDOCS-3702)B - #1460 - @traci707 
Indicate when done.
* ~~Check links with tool~~ -- skipped
* Check ToC -- @slsriehl, done
* Add redirects if needed 
* **Slug changes not detected**, huzzah!

Staging into master

---

docs/api-docs/channels/channel-webhooks.md
docs/api-docs/getting-started/webhooks/about-webhooks.md

3021B: about webhooks scope creep

---

docs/api-docs/getting-started/webhooks/about-webhooks.md

* [DEVDOCS-3762](https://jira.bigcommerce.com/browse/DEVDOCS-3762) - #1464 - @markcmurphy 
Indicate when done.
* ~Check links with tool~
* Check ToC -- @slsriehl done
* Add redirects if needed -- Slug changes not detected

Merge staging into master

---

toc.json

Stoplight throwing errors because of slug fields in TOC, attempting to undo

Troubleshoot toc error

---

docs/stencil-docs/reference-docs/global-objects-and-properties.md
toc.json

Fix Featured Product header

---

docs/api-docs/headless/checkout.md

updated link to the list of payment gateways

DEVDOCS-3759: date payment gateways link

---

docs/api-docs/toc.json

* Updating toc to test SL docs on custom slugs implementation instead of the generated id slugs.  https://meta.stoplight.io/docs/whats-new/ZG9jOjUwMjA3NTUy-april-2022-deployments

Testing custom slugs

---

toc.json

Need to update the TOC to display the BODL article.

DEVDOCS-3398: Add BODL to ToC

---

docs/stencil-docs/installing-stencil-cli/troubleshooting-your-setup.md

Updated language on 403 error troubleshooting docs

DEVDOCS-3909: Update troubleshooting-your-setup.md

---

docs/stencil-docs/localization/localizing-stores.md

DEVDOCS-3890: Add Spanish language files

---

docs/api-docs/payments/payments-api-overview.md

Updated example per feedback in [PR 1471](https://github.com/bigcommerce/dev-docs/pull/1471)

DEVDOCS-3803: Update payments-api-overview

---

docs/legacy/v2-products/v2-v3.md

1) Fixed broken links
2) Corrected a verb choice

DEVDOCS-3665: broken links

---

toc.json

Trying to fix the link to the handlebars-helpers-reference, not sure this will work.

DEVDOCS-3869: Update toc.json

---

docs/api-docs/channels/channel-webhooks.md
docs/api-docs/getting-started/webhooks/webhook-events.md

DEVDOCS-3021: Update channel-webhooks.md

---

docs/api-docs/customers/customer-login-api.md
docs/api-docs/storefront/graphql/graphql-api-overview.md

-added graphql logout mutation to graphql overview page
-added link to login/logout mutation from customer login api page

DEVDOCS-3708 graphql logout

---

docs/partner-apps/bundleb2b/b2b-edition.md

DEVDOCS-3882: Update b2b-edition.md

---

docs/api-docs/storefront/graphql/graphql-faceted-textual-search.md

DEVDOCS-3854: extended suggestions

---

docs/api-docs/cart-and-checkout/checkout-sdk.md

added a section describing how to update the checkout-sdk

DEVDOCS-3807: Update checkout-sdk

---

docs/api-docs/payments/payments-api-overview.md

DEVDOCS-4032 Update-payments-api-overview.md

---

docs/api-docs/payments/payments-api-overview.md

Adding Commonwealth Bank back to the list of Payment gateways

DEVDOCS-4026 add commonwealth bank to payments-api-overview

---

docs/api-docs/payments/payments-api-overview.md

Added Opayo Direct to the list of payment gateways supporting both stored instruments and raw card data.

DEVDOCS-4132: Update payments-api-overview

---

docs/api-docs/payments/payments-api-overview.md

Eric requested changing "Opayo Direct" to "Opayo by Elavon"

DEVDOCS-4132: Update payments-api-overview.md

---

docs/stencil-docs/deploying-a-theme/theme-best-practices.md

DEVDOCS-4238: Update theme-best-practices.md

---

docs/api-docs/payments/payments-api-overview.md
docs/stencil-docs/deploying-a-theme/theme-best-practices.md
package-lock.json
package.json

* no ticket - #1520 - dependabot
* [DEVDOCS-4238](https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4238) - #1555 - @traci707 
* [DEVDOCS-3858](https://bigcommercecloud.atlassian.net/browse/DEVDOCS-3858) - #1560 - @traci707

Staging to master

---

docs/api-docs/store-logs/store-logs.md
toc.json

DEVDOCS-4198 suggestions patch

---

docs/api-docs/getting-started/authentication.md
toc.json

* update broken link per ticket

DEVDOCS-4313: broken link per ticket

---

docs/api-docs/partner/subscriptions/foundation-guide.md
toc.json

* edits following new article review
* collaborative PR
cc @traci707

DEVDOCS-3922 (edit): Amend subscription foundation

---

docs/api-docs/tax/tax-properties.md

Changed up some of Sarah's edits and added new info. Fixed prose.

sarah's rewrites and notes

---

docs/api-docs/catalog/price-list-overview.md

DEVDOCS-4205 Price List API

---

docs/api-docs/storefront/graphql/graphql-api-overview.md

Edited what to press in UI to get to GraphQL Playground

DEVDOCS-4369: [edit] Update GraphQL Playground UI menu location

---

docs/api-docs/store-management/shipping/shipping-provider-api.md

* Added a new request of `- Your app's name`

fix(shipping): SHIPPING-700 Clarify carrier name request

---

docs/api-docs/partner/create-a-sandbox.md

Updated partner sandbox section

DEVDOCS-4203: [update] Modify partner sandbox reference

---

docs/stencil-docs/reference-docs/front-matter-reference.md

-Added sentence to clarify yml files should use single quotes or escaped double quotes
-Also Updated UI instructions

DEVDOCS-4286: [edit] Clarify double quotes for yml files 

---

docs/api-docs/partner/pos/pos-foundation-overview.md

DEVDOCS-3922: [suggestion branch] Create POS Foundation overview

---

docs/api-docs/partner/pos/foundation-guide.md
toc.json

* add dev blog link
* add POS Foundation to sidebar ToC 
[DEVDOCS-3922]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-3922?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-3922: [edit] POS Foundation, add post-publication links

---

docs/api-docs/channels/channel-webhooks.md

Made changes related to PDX-442. 
Documented store/channel/{channel_id}/settings/currency/updated webhook

Devdocs 3021 update channel webhooks

---

docs/api-docs/tax/tax-settings.md
toc.json

Related to:
-[PR 946](https://github.com/bigcommerce/api-specs/pull/946) (api spec)
-[PR 132](https://github.com/bigcommerce-labs/next-dev-center-prototype/pull/132) (redirects) 
ping @bc-ani

DEVDOCS-4399: [net new] Tax Settings

---

docs/api-docs/channels/channel-webhooks.md

no ticket
fixed a typo, changed updates to updated

(no ticket): [edit] Channel webhooks endpoint typo

---

docs/api-docs/getting-started/webhooks/about-webhooks.md

* replace several instances of `blacklist` with `blocklist`
* very minor other style changes
[DEVDOCS-4442]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4442?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-4442: [edit] Webhooks overview, replace blacklist with blocklist

---

docs/api-docs/partner/create-a-sandbox.md

Added global regions to partner sandbox creation

DEVDOCS-4425: [edit] Partner sandbox guide, add global regions

---

docs/stencil-docs/installing-stencil-cli/installing-stencil.md

Update Stencil CLI instructions

DEVDOCS-4395: [update] installation instructions for Stencil CLI

---

docs/api-docs/apps/guide/apps-09-ui.md
docs/api-docs/apps/guide/apps-12-requirements.md
docs/api-docs/apps/tutorials/sample-app-next/step-1-setup.md
docs/api-docs/apps/tutorials/sample-app-next/step-4-enhance-ux.md

* Updated links to BigDesign content in 4 files per recommendation from David Linke
No other changes
[DEVDOCS-4243]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4243?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOC-4243: Updated links to BigDesign content in 4 files

---

docs/api-docs/provider-apis/tax/overview.md

* Prevent broken link from upcoming Apps Guide edit
* Lint grammar
* Found during work on [DEVDOCS-2898]
[DEVDOCS-2898]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-2898?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

(no ticket): [maintenance] Tax Provider overview, link and grammar

---

docs/api-docs/building-storefronts/nextjs-commerce-guide.md

* add info about SSL/TSL cert
[DEVDOCS-3615]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-3615?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-3615: [value add] Headless Quickstart, info about SSL/TLS certificate

---

docs/api-docs/cart-and-checkout/add-to-cart-url.md

[DEVDOCS-4536](https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4536)
Removed `source` parameter from doc

DEVDOCS-4536: [maintenance] source parameter

---

assets/csv/tracking_carrier_values.csv

* Update `tracking_carrier` values
[DEVDOCS-4393]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4393?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-4393 [value add] Update Tracking Carrier values

---

docs/stencil-docs/storefront-customization/custom-templates.md

Created a sub-section to add information about template associations.
[DEVDOCS-4427]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4427?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-4427: [value add] Custom Templates, info re associations

---

docs/api-docs/apps/guide/apps-09-ui.md

no ticket
I saw the typo and wanted to fix it.

(no ticket): [fix typo] Apps Guide, UI article

---

docs/api-docs/partner/subscriptions/foundation-guide.md

Updates based on the ticket requirements

DEVDOCS-4413: [update] Subscription Foundation, add Vercel support

---

docs/api-docs/cart-and-checkout/open-source-checkout.md

Noticed that the image needed updating

(no ticket): [update] Open source checkout, image update

---

docs/api-docs/getting-started/about-our-api.md
docs/api-docs/getting-started/api-status-codes.md
docs/api-docs/getting-started/best-practices.md
docs/api-docs/getting-started/building-apps-bigcommerce/types-of-apps.md
docs/api-docs/getting-started/rest-api-authentication.md

* some links
[DEVDOCS-4621]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4621?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-4621: [links] Remove /basics/ per redirects file

---

docs/stencil-docs/installing-stencil-cli/live-previewing-a-theme.md

Add Serving theme over HTTPS section
[DEVDOCS-4572]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4572?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-4572: [value add request ] Suggest ngrok to serve theme over https

---

docs/stencil-docs/page-builder/configuration.md
docs/stencil-docs/reference-docs/styles-and-properties.md

Added a new "sort" type for Theme Styles
According to [DEVDOCS-4509](https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4509)

DEVDOCS-4509: [update] Stencil, add new sort type for theme styles

---

docs/api-docs/payments/payments-api-overview.md

Added a note
[DEVDOCS-4604]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4604?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-4604: [add] Payments, add ref to Get stored instruments

---

docs/api-docs/staging/staging-pro-overview.md
toc.json

* Add overview of StagingPro service
[DEVDOCS-3785]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-3785?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-3785: [net new] StagingPro overview

---

docs/stencil-docs/installing-stencil-cli/stencil-cli-options-and-commands.md

* @AndrewBarber submitted 
* #1691
* #1692 
[DEVDOCS-4655]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4655?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-4655: [update] Stencil CLI commands

---

docs/api-docs/payments/payments-api-overview.md

Added BNZ to the Payments API, gateway supports both Stored Instruments and Raw Card data
[DEVDOCS-4277]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4277?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-4277: [add] BNZ works with Payments API

---

docs/bigcommerce-for-wordpress/setup/multi-site.md
docs/stencil-docs/localization/localizing-stores.md
docs/stencil-docs/reference-docs/global-objects-and-properties.md

update menu paths
[DEVDOCS-4270]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4270?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-4270: [update] MSF control panel UI references

---

docs/msf/msf-api-guide.md

Update text to clear ambiguity regarding fields to activate themes.
[DEVDOCS-4647]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4647?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-4647: [clarify] MSF theme parameters

---

docs/api-docs/tax/tax-rates-zones.md
toc.json

This PR is related to:
-[PR 945](https://github.com/bigcommerce/api-specs/pull/945): API Spec
-[PR 133](https://github.com/bigcommerce-labs/next-dev-center-prototype/pull/133): redirects

DEVDOCS-4400: [net new] Tax Rates Zones

---

docs/api-docs/tax/tax-rates-zones.md

Added notes about default tax zones and zones 
[DEVDOCS-4680]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4680?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-4680: [update] Tax Rates & Zones, more about default tax zone

---

docs/api-docs/analytics/bodl-for-storefronts.md

* rollback unintentional edit to BODL
Co-authored-by: Mark Murphy <mark.murphy@bigcommerce.com>

(no ticket): [rollback] BODL, unintentional edit

---

docs/api-docs/storefront/graphql/graphql-api-overview.md

Added complexity header for graphql responses
[DEVDOCS-4671]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4671?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-4671: [new] GraphQL Storefront API, add complexity response header

---

docs/stencil-docs/reference-docs/styles-and-properties.md

added text explaining `force_reload`
[DEVDOCS-4660]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4660?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-4660: [update] Theme Styles and Properties, clarify force_reload

---

docs/legacy/v2-catalog-products/v2-custom-fields.md

Fixed broken link
[DEVDOCS-4710]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4710?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-4710: [update] Catalog V2 API, fix broken link

---

docs/stencil-docs/reference-docs/stencil-utils-api-reference.md

Added getPageByGQL to stencil docs
[DEVDOCS-4688]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4688?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-4688: [new] Stencil Ref, add getPageByGQL

---

docs/bigcommerce-for-wordpress/setup/multi-site.md

* Update the OAuth scopes default settings
* Style guide edits
[DEVDOCS-4576]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4576?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEVDOCS-4756]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4756?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-4756: [update] BC4WP Setup, update list of default OAuth scope settings

---

docs/stencil-docs/installing-stencil-cli/live-previewing-a-theme.md

remove outdated youtube video
[DEVDOCS-4759]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4759?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-4759: [remove] Live Previewing a Theme, remove outdated YouTube video

---

docs/stencil-docs/reference-docs/handlebars-helpers-reference.md

*  Add each to list of standard helpers

(no ticket): [update] Handlebars helpers, add each to list of standard helpers

---

docs/legacy/v2-catalog-products/v2-product-sku.md
docs/legacy/v2-catalog-products/v2-products.md

* refine 207 response object description.
[DEVDOCS-4768]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4768?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-4768: [suggest] Products V2, PR 1793 

---

docs/legacy/v2-catalog-products/v2-product-sku.md
docs/legacy/v2-catalog-products/v2-products.md
docs/stencil-docs/reference-docs/handlebars-helpers-reference.md

Added descriptions of 207 status code for Create Product, Update Product, Create Product SKU and Update Product SKU for v2
Updated the following files:
*v2-products.md
*v2-product-sku.md
[DEVDOCS-4768]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4768?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-4768: [update] Products V2, add description of 207 status code

---

docs/api-docs/getting-started/available-apis.mdx

Updated the syntax for migration and changed the extension to .mdx
[DEVDOCS-4719]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4719?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-4719 : [migrate] Available APIs, syntax

---

docs/api-docs/headless/customers.mdx
docs/partner-apps/bundleb2b/b2b-edition.mdx

Links to Stoplight
[DEVDOCS-4719]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4719?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-4719: [migrate] Stoplight links

---

docs/bigcommerce-for-wordpress/extending-the-plugin/amp-for-the-plugin.mdx
docs/bigcommerce-for-wordpress/extending-the-plugin/bigcommerce-for-wordpress-cron.mdx
docs/bigcommerce-for-wordpress/extending-the-plugin/code-reference.mdx
docs/bigcommerce-for-wordpress/extending-the-plugin/customization-guide.mdx
docs/bigcommerce-for-wordpress/getting-started/install.mdx
docs/bigcommerce-for-wordpress/getting-started/supported-features.mdx

Updated the following BigCommerce MDX files to match TOC:
- docs/bigcommerce-for-wordpress/extending-the-plugin/amp-for-the-plugin.mdx
- docs/bigcommerce-for-wordpress/extending-the-plugin/bigcommerce-for-wordpress-cron.mdx
- docs/bigcommerce-for-wordpress/extending-the-plugin/code-reference.mdx
- docs/bigcommerce-for-wordpress/extending-the-plugin/customization-guide.mdx
- docs/bigcommerce-for-wordpress/getting-started/install.mdx
- docs/bigcommerce-for-wordpress/getting-started/supported-features.mdx
[DEVDOCS-4719]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4719?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Update BC4WP titles

---

docs/api-docs/apps/apps-quick-start.mdx
docs/api-docs/apps/guide/apps-04-devloper-portal.mdx
docs/api-docs/apps/guide/apps-05-oauth.mdx
docs/api-docs/channels/channel-app-best-practices.mdx
docs/api-docs/channels/channel-app-requirements.mdx
docs/api-docs/channels/channels-extending-existing.mdx
docs/api-docs/customers/current-customer-api.mdx
docs/api-docs/getting-started/authentication.mdx
docs/api-docs/getting-started/rest-api-authentication.mdx
docs/api-docs/orders/orders-api-overview.mdx
docs/api-docs/orders/orders-overview.mdx
docs/api-docs/payments/payments-api-overview.mdx
docs/api-docs/storefront/widgets/product-widget-tutorial.mdx
docs/api-docs/storefront/widgets/widget-builder.mdx
docs/api-docs/webhooks/setting-up-webhooks.mdx
docs/stencil-docs/page-builder/third-party-widgets.mdx

auth docs new links

---

docs/api-docs/storefront/widgets/widget-builder.mdx

* fixes error in Dev Center parsing

(no ticket): [update] Widget Builder, remove shell tags from code block

---

docs/api-docs/storefront/widgets/widget-builder.mdx

Staging into main

---

docs/api-docs/users/overview.mdx

Update users api docs

---

docs/api-docs/users/overview.mdx

- [DEVDOCS-4838](https://github.com/bigcommerce/dev-docs/pull/1835) - [PR#1835](https://github.com/bigcommerce/dev-docs/pull/1835)
[DEVDOCS-4838]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4838?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Rebase Staging to Main

---

docs/api-docs/payments/payments-api-overview.mdx

Added Adyen v3 oauth to the compatible gateway table
[DEVDOCS-4562]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4562?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-4562:[Update] adyenv3

---

docs/api-docs/headless/channels.mdx

Added limits to channels.mdx
[DEVDOCS-4819]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4819?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-4819:[update] channels.mdx

---

docs/stencil-docs/reference-docs/global-objects-and-properties.mdx

Created a child branch to incorporate some changes that need to be made.

Fix table issues

---

docs/api-docs/headless/channels.mdx
docs/api-docs/payments/payments-api-overview.mdx
docs/api-docs/store-management/shipping/shipping-provider-api.mdx
docs/api-docs/users/overview.mdx
docs/stencil-docs/reference-docs/handlebars-helpers-reference.mdx

[DEVDOCS-4838: [update] Users API, Update steps in Overview.mdx](https://github.com/bigcommerce/dev-docs/commit/411acbcf638521f2da6182711bbfa0bd6cb10786)
Authored by @bc-tgomez 
[fix(shipping): SHIPPING-700 Remove unused x-auth-token header](https://github.com/bigcommerce/dev-docs/commit/db6ebd15624fcf5bcf8efd441546651b17c6c997)
Authored by @agchan12 
[DEVDOCS-4562:[Update] adyenv3](https://github.com/bigcommerce/dev-docs/commit/8edde8d6773b480f2606cfb976845c7a19fb6390)
Authored by @bc-traciporter 
[DEVDOCS-4750: [update] Handlebars helpers, add JSONparseSafe](https://github.com/bigcommerce/dev-docs/commit/7762f216c2eee0dfbe12835dbb161285394dbf71)
Authored by @Traci, with contributions from @bc-andreadao @slsriehl @RomanKrasinskyi @thearticalex @bc-tgomez

Merge Staging into Main

---

docs/api-docs/getting-started/rest-api-authentication.mdx

Add supporting account-level API info to the **API Accounts & Oath Scopes** doc

Child branch created to add supporting info

---

docs/stencil-docs/reference-docs/handlebars-helpers-reference.mdx

DEVDOCS-4750 added JSONParseSafe, but I forgot to list it under standard helpers.

DEVDOCS-4750: [revision] add to list

---

docs/api-docs/storefront/graphql/graphql-api-overview.mdx

It is recommended to review this PR commit-by-commit.
- Remove erroneous reference to OAuth which was confusing
- Add clarifications to "early access" status of the API
- Polish the overview article and update the example queries used to improve them based on the current state of the API

Polishing GQL overview

---

docs/api-docs/provider-apis/tax/overview.mdx
docs/bigcommerce-for-wordpress/setup/multi-site.mdx

Merging Staging to Main (#1864)

---

docs/api-docs/users/Account-level-API-accounts.mdx
docs/api-docs/users/overview.mdx

[DEVDOCS-4635](https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4635)
**What changed:**
* New Account-level API account doc
**Related Notes:**
* Updating [PR#1840](https://github.com/bigcommerce/dev-docs/pull/1840)
Authored by Constanze Kratel <constanze.kratel@bigcommerce.com>
[DEVDOCS-4635]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4635?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-4635: [new] Users, Account-level API accounts

---

docs/api-docs/apps/apps-quick-start.mdx
docs/api-docs/apps/guide/apps-11-best-practices.mdx
docs/api-docs/headless/channels.mdx
docs/api-docs/partner/pos/foundation-guide.mdx
docs/api-docs/partner/subscriptions/foundation-guide.mdx
docs/api-docs/payments/payments-api-overview.mdx
docs/api-docs/provider-apis/tax/overview.mdx
docs/api-docs/store-management/shipping/shipping-provider-api.mdx
docs/api-docs/storefront/graphql/graphql-api-overview.mdx
docs/api-docs/users/Account-level-API-accounts.mdx
docs/api-docs/users/overview.mdx
docs/bigcommerce-for-wordpress/setup/multi-site.mdx
docs/stencil-docs/configure-store-design-ui/defining-global-styles.mdx
docs/stencil-docs/getting-started/stencil-technology-stack.mdx
docs/stencil-docs/getting-started/transitioning-to-stencil.mdx
docs/stencil-docs/installing-stencil-cli/installing-stencil.mdx
docs/stencil-docs/installing-stencil-cli/live-previewing-a-theme.mdx
docs/stencil-docs/installing-stencil-cli/stencil-cli-options-and-commands.mdx
docs/stencil-docs/installing-stencil-cli/troubleshooting-your-setup.mdx
docs/stencil-docs/localization/localization-tutorial.mdx
docs/stencil-docs/localization/translation-keys.mdx
docs/stencil-docs/reference-docs/global-objects-and-properties.mdx
docs/stencil-docs/reference-docs/handlebars-helpers-reference.mdx

Grouped by the representative PR on main
* #1842
* #1730
* #1819
* #1828
* #1811
* #1835
* Merge remote staging into staging
* #quick-fix unescaped hbs
* #1844
* Restore hbs (revert 1730 + add work back)
* Redo quick fix unescaped hbs
* #1850
* #1734
* #1846
* #1847
* #1853
* #1848 (originated on main)
* #1862
* #1855
* #1860 (revert 1855)
* #1861
* #1864
* #1741
* #1728
* #1868
* #1867
* #1841
* #1876
* #1857
* #1730
* #1819
* #1828
* #1811
* #1835
* quick-fix unescaped hbs
* Restore hbs (revert 1730 + add branch work back)
* Redo quick fix unescaped hbs
* #1734
* #1846
* #1847
* #1848 (originated on main)
* #1855
* #1860 (revert 1855)
* #1861
* #1741
* #1728
* #1867
* #1841
* #1857

Merging staging to main

---

docs/stencil-docs/reference-docs/handlebars-helpers-reference.mdx

* Restore older reference to acceptlist
* Change another instance of whitelist to acceptlist

(no ticket): [update] Handlebars helpers, change whitelist to acceptlist

---

docs/bigcommerce-for-wordpress/setup/multi-site.mdx

Update OAuth scopes to reflect accuracy

DEVDOCS-4864: [update] BC4WP, OAuth scopes

---

docs/api-docs/apps/apps-quick-start.mdx

* Add a step to configure an app's `remove_user` callback
* support for multi-user
[DEVDOCS-4876]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4876?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-4876: [update] Apps Quick Start, add remove_user callback config

---

docs/stencil-docs/reference-docs/handlebars-helpers-reference.mdx

Merging to `main`:
*  [#PR 1877](https://github.com/bigcommerce/dev-docs/pull/1877)

Merging to Main

---

docs/api-docs/getting-started/best-practices.mdx
docs/api-docs/management-apis/email-templates/overview.mdx
docs/api-docs/storefront/scripts-overview.mdx
docs/stencil-docs/configure-store-design-ui/defining-global-styles.mdx
docs/stencil-docs/customizing-checkout/checkout-confirmation-injection.mdx

* change comments and code blocks to troubleshoot preview builds

(no ticket): [revise] Many, revise syntax to support test deploys

---

docs/api-docs/users/overview.mdx

* clarify account-related language, 
* make links relative and add anchor info, 
* standardize control panel references, 
* style guide stuff
[DEVDOCS-4887]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4887?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-4887: child PR

---

docs/api-docs/users/overview.mdx

[DEVDOCS-4887](https://jira.bigcommerce.com/browse/DEVDOCS-4887)
**What changed**
* Update Account Stores Users from Account Stores
* Update Account Stores Users query and json
[DEVDOCS-4887]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4887?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-4887: [revise] GraphQL Users API, account stores users update

---

docs/stencil-docs/javascript-and-event-hooks/npm-tutorials.mdx

DEVDOCS-4902: [update] fix image

---

docs/stencil-docs/reference-docs/handlebars-helpers-reference.mdx

[DEVDOCS-4908](https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4908)
[DEVDOCS-4908]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4908?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-4908: [update] remove sentence in cors section

---

docs/stencil-docs/installing-stencil-cli/installing-stencil.mdx

[DEVDOCS-4906](https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4906)
Changed the order of steps to look at a live preview of a theme to match the steps listed in the Live Previewing a Theme article.
[DEVDOCS-4906]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4906?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-4906: [update] change order of steps for live previewing

---

docs/api-docs/catalog/products-overview.mdx

I came across this typo while looking for something else.
ping {names}

(no ticket): [update] Catalog Overview, fix typo

---

docs/api-docs/channels/building-channel-apps.mdx

Fixed many broken links on this page reported by Ben Ackles and Seamus Duffy
[DEVDOCS-4914]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4914?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-4914: [update] Building Channel apps, fix broken links

---

docs/stencil-docs/customizing-checkout/open-source-checkout.mdx

no ticket
Fixed the _Install using the V3 Checkout API_ link
* 
ping {names}

(no ticket): [update] Open Source Checkout, fix link

---

docs/api-docs/channels/channels-storefront-tutorial.mdx

* Update the list of available protected UI sections for channel menus
* Updates for style and clarity
* [api-specs PR #1319](https://github.com/bigcommerce/api-specs/pull/1319)
ping {names}
[DEVDOCS-4847]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4847?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-4847: [update] Building Storefront Channels, update protected UI settings

---

docs/api-docs/provider-apis/tax/overview.mdx

- Remove unnecessary terminology
[DEVDOCS-5000]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5000?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5000: [revise] Tax Provider API, improve clarity

---

.github/workflows/deploy.yml

- [SELFDEV-216]
[SELFDEV-216]: https://bigcommercecloud.atlassian.net/browse/SELFDEV-216?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SELFDEV-216: [dev] add deploy hook and GH action

---

docs/api-docs/customers/customer-login-api.mdx
docs/api-docs/getting-started/about-our-api.mdx
docs/api-docs/storefront/graphql/graphql-api-examples.mdx
docs/api-docs/storefront/graphql/graphql-api-overview.mdx

* rollback
* #1940
[DEVDOCS-5036]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5036?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5036: [rollback] mis-synchronized updates

---

docs/api-docs/storefront/graphql/graphql-carts-and-checkout.mdx

* update payments links
* indent code blocks to facilitate folding code
* update spacing
* add all the links in the document to the resources section per our usual format
* #1940
[DEVDOCS-5037]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5037?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5037: [child] GraphQL Storefront Carts & Checkout

---

docs/bigcommerce-for-wordpress/setup/troubleshooting.mdx

* Received a PR to add more troubleshooting tips
* Applied troubleshooting style guide to doc
* Made editorial edits 
* New troubleshooting topics are added to the doc now
Parent PR: https://github.com/bigcommerce/dev-docs/pull/1944
ping @chanceaclark 
[DEVDOCS-5063]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5063?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5063: [revise] BigCommerce For WordPress, Troubleshooting guide revision

---

docs/api-docs/storefront/graphql/graphql-carts-and-checkout.mdx
docs/api-docs/storefront/graphql/graphql_carts_and_checkout.mdx

create new article for GraphQL Storefront Carts & Checkout
* 
* #1957 
* #1958 
ping {names}
[DEVDOCS-5037]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5037?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5037: [new] GraphQL Cart and Checkout

---

docs/api-docs/building-checkouts/checkout-consignment.mdx
docs/api-docs/cart-and-checkout/embedded-checkout-tutorial.mdx
docs/api-docs/cart-and-checkout/working-sf-apis.mdx
docs/api-docs/catalog/currencies/how-currencies-work.mdx
docs/api-docs/getting-started/authentication.mdx
docs/api-docs/getting-started/filtering.mdx
docs/api-docs/getting-started/making-requests.mdx
docs/api-docs/headless/customers.mdx
docs/api-docs/payments/payments-api-overview.mdx
docs/api-docs/store-management/shipping/shipping-overview.mdx
docs/api-docs/storefront/graphql/graphql-api-overview.mdx

* 
* #1953
[DEVDOCS-5037]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5037?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5037: [update] Many, incorporate GraphQL Storefront Carts

---

.github/workflows/deploy.yml

* Enable manual action dispatch with the option to build with or without cache
None
ping @slsriehl

(no ticket): [dev] Enable manual build action

---

docs/api-docs/webhooks/webhook-events.mdx

Remove "Variant - deleted" from the list under Product update events
ping {names}
[DEVDOCS-4777]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4777?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-4777: [update] Variant - deleted

---

docs/stencil-docs/reference-docs/front-matter-reference.mdx

* fix code indentation error
* #1952
ping @bc-traciporter @pieterdnz
[DEVDOCS-5100]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5100?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5100: [update] Stencil Frontmatter, fix code block indentation

---

docs/stencil-docs/getting-started/stencil-technology-stack.mdx

Add new sub-section called "Migration handlebars v3 to v4"
* 
ping {names}
[DEVDOCS-4944]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4944?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-4944: [update]update stencil technology stack

---

docs/stencil-docs/developing-further/modifying-forms.mdx

Add a note
ping {names}
[DEVDOCS-4779]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4779?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-4779: [update] Update modifying-forms.mdx

---

docs/api-docs/storefront/widgets/widget-builder.mdx

* Update node & npm versions
* Update API account and OAuth scope info
ping @bc-andreadao
[DEVDOCS-5125]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5125?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5125: [update] Widget Builder, node & npm versions

---

docs/api-docs/apps/tutorials/sample-app-next/step-4-enhance-ux.mdx
docs/api-docs/catalog/products-overview.mdx
docs/api-docs/catalog/v2-v3-examples.mdx
docs/api-docs/catalog/v2-vs-v3.mdx
docs/api-docs/headless/products.mdx

* Add frontmatter with several syntaxes
ping @bc-shawnyap

(no ticket): [test] Multiple, add frontmatter with keywords

---

docs/stencil-docs/reference-docs/handlebars-helpers-reference.mdx

* Remove problematic characters
ping @bc-shawnyap @markcmurphy

(no ticket): [dev] Meta parse error fix

---

docs/stencil-docs/reference-docs/handlebars-helpers-reference.mdx

* Handlebars helpers, remove meta
ping {names}

(no ticket): [dev] Handlebars helpers, remove meta

---

docs/api-docs/catalog/price-list-overview.mdx
docs/api-docs/customers/customers-subscribers-overview.mdx

(no ticket): [dev] Many, remove meta from problematic files

---

docs/api-docs/webhooks/setting-up-webhooks.mdx

Added example to clarify destination URL structure
* 
ping {names}
[DEVDOCS-3904]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-3904?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-3904: [update] clarify structure for destination

---

docs/api-docs/storefront/graphql/graphql-api-overview.mdx

- More explanation on complexity header
[DEVDOCS-5010]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5010?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5010 [new]: GQL Storefront API, complexity header

---

docs/api-docs/catalog/currencies/how-currencies-work.mdx

Provide a bulleted list in the present tense.
* Fix broken link in the "How Currencies Work" article.
* Search the repo for duplicates of the bad link.
* Redirect work remains.
ping @markcmurphy
[SELFDEV-271]: https://bigcommercecloud.atlassian.net/browse/SELFDEV-271?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SELFDEV-271: [update] Currencies, fix broken link

---

docs/api-docs/getting-started/rest-api-authentication.mdx

* update users overview links
ping @bc-tgomez
[DEVDOCS-5136]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5136?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5136: [update] API Accounts, links to users overview

---

docs/api-docs/cart-and-checkout/add-to-cart-url.mdx
docs/api-docs/catalog/currencies/how-currencies-work.mdx
docs/api-docs/channels/channels-extending-existing.mdx
docs/api-docs/channels/channels-storefront-tutorial.mdx
docs/api-docs/partner/pos/channels-pos-tutorial.mdx

* Update lists of channels types
ping @bc-nathanielolson
[DEVDOCS-4907]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4907?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-4907: [update] Channels various, link to channels platform types

---

docs/api-docs/storefront/graphql/graphql-api-examples.mdx

* add http config to code samples
ping @bc-andreadao
[DEVDOCS-5131]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5131?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5131: [update] GQLSF Code Samples, add HTTP config

---

docs/api-docs/webhooks/about-webhooks.mdx

* 
ping {names}
[DEVDOCS-5236]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5236?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5236: [update] update blocklisting mechanism info

---

docs/legacy/blueprint-reference/blueprint-snippets.mdx

Replaced "Available Variables" with the sub-heading so the right-side navigation is more useful.
In addition, I removed the definition column since they were all empty.
ping {names}
[DEVDOCS-5154]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5154?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5154: [update] Update blueprint-snippets.mdx

---

docs/stencil-docs/customizing-checkout/checkout-sdk-example.mdx
docs/stencil-docs/customizing-checkout/checkout-sdk-quickstart.mdx
docs/stencil-docs/customizing-checkout/open-source-checkout.mdx

* 
ping {names}
[DEVDOCS-4953]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4953?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-4953: [revise] audit and rewrite

---

docs/api-docs/apps/guide/apps-06-callbacks.mdx

* modify jwt claims descriptions
* link to a list of jwt handling libraries
ping {names}
[DEVDOCS-4514]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4514?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-4514: [update] App Callbacks, modify jwt claims descriptions

---

docs/api-docs/getting-started/about-our-api.mdx
docs/api-docs/getting-started/api-status-codes.mdx
docs/api-docs/getting-started/authentication.mdx
docs/api-docs/getting-started/best-practices.mdx
docs/api-docs/getting-started/filtering.mdx

(no ticket): [update] Various, spacing

---

docs/api-docs/getting-started/about-our-api.mdx
docs/api-docs/getting-started/best-practices.mdx
docs/api-docs/headless/overview.mdx

* add ID to table of request headers, add descriptions to best practices and headless overview
ping @bc-cbrisky
[DEVDOCS-4692]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4692?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DEVDOCS-4622]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4622?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-4622: [new] X-Correlation-Id header for headless storefront requests

---

docs/api-docs/headless/overview.mdx

* update code block meta syntax
ping {names}
[DEVDOCS-4622]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4622?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-4622: [update]  X-Correlation-Id, fix code block meta

---

docs/api-docs/webhooks/webhook-events.mdx

See https://bigcommerce.slack.com/archives/C57SQ401K/p1693927280537999
ping {names}

DEVDOCS-5415: [update] Update store/order/create

---

docs/api-docs/partner/support.mdx

Clarified how to subscribe to the RSS feed in the changelog section
ping {names}
[DEVDOCS-5449]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5449?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5449: [update]Update changelog information

---

docs/api-docs/getting-started/deprecations-and-sunsets.mdx
docs/api-docs/partner/staying-current.mdx

Updating additional references to the changelog feed.
ping {names}
[DEVDOCS-5449]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5449?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5449: [Update] changelog information

---

docs/api-docs/getting-started/rest-api-authentication.mdx

* Add OAuth scopes
[DEVDOCS-4889]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4889?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-4889: [new] Stored Instruments, add oauth scopes

---

docs/api-docs/apps/guide/apps-01-introduction.mdx
docs/api-docs/partner/support.mdx
docs/stencil-docs/deploying-a-theme/troubleshooting-theme-uploads.mdx
docs/stencil-docs/getting-started/about-stencil.mdx

Update community link to https://developer.bigcommerce.com/community
ping {names}
[DEVDOCS-5062]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5062?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5062: [update]update community link

---

docs/api-docs/getting-started/api-status-codes.mdx

Added 499 response code
ping {names}
[DEVDOCS-5454]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5454?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5454 [Update] Add 499 response code

---

docs/api-docs/partner/create-a-sandbox.mdx

Added limits and resized a few images
ping {names}
[DEVDOCS-5502]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5502?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5502: [update] Resized images and add limits

---

docs/start/introduction-to-bigcommerce.mdx

* new intro to bc article
ping @becomevocal

(no ticket): [new] Intro to BigCommerce 

---

docs/stencil-docs/installing-stencil-cli/node-sass.mdx

* article stub
ping {names}
[SELFDEV-410]: https://bigcommercecloud.atlassian.net/browse/SELFDEV-410?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SELFDEV-410: [new] Stencil, add node-sass article

---

docs/stencil-docs/installing-stencil-cli/node-sass.mdx

Added upgrade doc
ping {names}
[DEVDOCS-4761]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4761?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-4761: [Update]Add node-sass update doc

---

docs/api-docs/storefront/graphql/graphql-api-overview.mdx

- Changed images to reflect new playground
[DEVDOCS-5574]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5574?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5574 [update]: GQL SF API, change images to new playground

---

docs/stencil-docs/developing-further/customizing-invoices.mdx

* update sunsetting link
ping {names}

(no ticket): [update] Links

---

CODE_OF_CONDUCT.md

[No Ticket] Add code of conduct to the directory.
* Adds the Open Source Code of Conduct file to this repository because it accepts community contributions.
Nope

[No Ticket] Add code of conduct

---

docs/stencil-docs/developing-further/customizing-invoices.mdx

* update link to email invoice reference
ping {names}
[DEVDOCS-5650]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5650?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5650: [update] Customizing Invoices, update link to email reference

---

docs/api-docs/partner/becoming-a-partner.mdx

Correct navigation 
ping {names}
[DEVDOCS-5619]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5619?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5619: [Update] becoming-a-partner.mdx

---

docs/api-docs/storefront/graphql/graphql-api-overview.mdx

Added to the FAQ
ping {names}
[DEVDOCS-5675]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-5675?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-5675: [update] add graphQL behavior

---

pull_request_template.md

(no ticket): [repo] PR template, add release notes section

---

docs/msf/msf-overview.mdx

Added a reference to the Multi-Storefront KB article
No release notes as this update was made a year ago.
* 
ping {names}
[DEVDOCS-4492]: https://bigcommercecloud.atlassian.net/browse/DEVDOCS-4492?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DEVDOCS-4492: [update] MSF Overview, add KB reference
